export const SELECT_EVENT = 'SELECT_EVENT';
export const SET_HOVERED_STATUS = 'SET_HOVERED_STATUS';
export const ZOOM_CHANGED = 'ZOOM_CHANGED';
export const MOUSE_MOVED = 'MOUSE_MOVED';
export const WINDOW_RESIZED = 'WIDNOW_RESIZED';
