import uuid from 'uuid/v4';

const rawEvents = [
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'Das erste künstliche Neuron',
		text: 'Im Jahr 1943 erzeugen die Wissenschaftler Warren McCulloch und Walter Pitts die ersten universalen, künstlichen Neuronen. Dieser Fortschritt wird als Meilenstein in der Geschichte der Künstlichen Intelligenz angesehen.',
		startDate: new Date('1942-12-31T23:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'https://en.wikipedia.org/wiki/Artificial_Intelligence:_A_Modern_Approach',
		],
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'Jon Gold, KI–Designer bei Airbnb, warnt Designer*innen davor, den Fortschritt der künstlichen Intelligenz zu ignorieren.',
		text: 'Friday realtalk: design as a profession will look unrecognizably different in 15 years due to AI. time to stop burying heads in sand.',
		startDate: new Date('2017-04-06T22:00:00.000Z'),
		type: 'social',
		externalLinks: [
			'https://twitter.com/jongold/status/850533033698508800',
		],
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'Patrick Hebron: Machine Learning for Designers',
		startDate: new Date('2016-06-08T22:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'http://www.oreilly.com/design/free/files/machine-learning-for-designers.pdf',
		],
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'Andrew Yan-Tak Ng, ehemals Head of Google Brain, fasst den Fortschritt von Künstlicher Intelligenz zusammen.',
		text: 'Pretty much anything that a normal person can do in <1 sec, we can now automate with AI.',
		startDate: new Date('2016-10-17T22:00:00.000Z'),
		type: 'social',
		externalLinks: [
			'https://twitter.com/AndrewYNg/status/788548053745569792',
		],
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'AlphaGo versus Lee Sedol',
		text: 'Künstliche Intelligenz besiegt Mensch im Spiel AlphaGo.',
		startDate: new Date('2016-03-08T23:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'https://en.wikipedia.org/wiki/AlphaGo_versus_Lee_Sedol',
		],
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'KI-Forscher Herbert Simon überschätzt das Potenzial von Maschinen',
		text: '"Machines will be capable, within twenty years, of doing any work a man can do."',
		startDate: new Date('1955-12-31T23:00:00.000Z'),
		type: 'quote',
		externalLinks: [
			'https://www.digitaltrends.com/features/top-10-bad-tech-predictions/5/',
		],
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'KI–Forscher Marvin Minsky überschätzt das Potenzial von Maschinen',
		text: '"Within a generation [...] the problem of creating \'artificial intelligence\' will substantially be solved."',
		startDate: new Date('1955-12-31T23:00:00.000Z'),
		type: 'quote',
		externalLinks: [
			'Crevier, Daniel (1993), AI: The Tumultuous Search for Artificial Intelligence, New York, NY: BasicBooks, ISBN 0-465-02997-3',
		],
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'Künstliche Intelligenz wird eigenständiges Forschungsfeld',
		startDate: new Date('1956-06-17T23:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'http://www-formal.stanford.edu/jmc/history/dartmouth/dartmouth.html',
		],
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'Benefits & Risks of Artificial Intelligence',
		text: '“Everything we love about civilization is a product of intelligence, so amplifying our human intelligence with artificial intelligence has the potential of helping civilization flourish like never before – as long as we manage to keep the technology beneficial.“ — Max Tegmark, President of the Future of Life Institute',
		startDate: new Date('2016-05-29T22:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'https://futureoflife.org/background/benefits-risks-of-artificial-intelligence/',
		],
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'Elon Musk geht davon aus, dass Künstliche Intelligenz zwischen 2030 und 2040 dem Menschen überlegen sein wird.',
		text: 'AI will be able to beat us at everything. [...] closer to 2030, 2040 imo. 2060 would be a linear extrapolation, but progress is exponential.',
		startDate: new Date('2017-06-04T22:00:00.000Z'),
		type: 'social',
		externalLinks: [
			'https://twitter.com/elonmusk/status/871886151014940672',
		],
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: '„KI Winter“',
		text: 'Als „KI Winter“ wird ein nicht genau bestimmter Zeitraum in den 70er Jahren beschrieben, in dem der mit KI verbundene Enthusiasmus einen Tiefpunkt erreichte. ',
		startDate: new Date('1975-04-30T23:00:00.000Z'),
		enddatumDesEintragsOptional: '1979-12-30T23:00:00.000Z',
		type: 'event',
		externalLinks: [
			'https://en.wikipedia.org/wiki/AI_winter',
		],
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'The Grid steigert Wert um $4.6M durch intelligenten Website–Baukasten',
		startDate: new Date('2014-12-01T23:00:00.000Z'),
		type: 'web',
		externalLinks: [
			'https://thegrid.io',
			'https://techcrunch.com/2014/12/02/the-grid-raises-4-6m-for-its-intelligent-website-builder/',
		],
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: '„Expert Systems“ leiten den ersten kommerziellen Erfolg von KI ein',
		startDate: new Date('1979-12-31T23:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'https://en.wikipedia.org/wiki/Expert_system',
		],
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'Top 20 Filme – Künstliche Intelligenz',
		startDate: new Date('1920-12-31T23:00:00.000Z'),
		enddatumDesEintragsOptional: '2017-07-14T22:00:00.000Z',
		type: 'text',
		externalLinks: [
			'https://www.theguardian.com/culture/gallery/2015/jan/08/the-top-20-artificial-intelligence-films-in-pictures',
		],
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'Das Programm „Deep Blue“ besiegt den Schachweltmeister Gary Kasparov',
		startDate: new Date('1997-05-10T22:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'https://de.wikipedia.org/wiki/Deep_Blue',
		],
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'Interaction Designers vs. Algorithms',
		text: 'Giles Colborne about designers\' skills in the context of AI.',
		startDate: new Date('2016-03-31T22:00:00.000Z'),
		type: 'video',
		videourlFallsEinVideoHinzugefgtWerdenSoll: 'https://vimeo.com/161177402',
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'IDEO veröffentlicht Font Map',
		text: 'Font Map ist ein Deep Learning Algorithmus, der Typografie analysieren und organsieren kann.',
		startDate: new Date('2017-04-19T22:00:00.000Z'),
		type: 'web',
		externalLinks: [
			'http://fontmap.ideo.com/',
		],
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'Google wechselt Ansatz von \'mobile first\' zu \'AI first\'',
		text: 'Bei der Google IO im Mai 2017 wechselt Google die Richtung des Unternehmens und verkündet große Investitionen in AI.',
		startDate: new Date('2017-05-16T22:00:00.000Z'),
		enddatumDesEintragsOptional: '2017-05-19T22:00:00.000Z',
		type: 'video',
		externalLinks: [
			'https://www.youtube.com/watch?v=Y2VF8tmLFHw',
			'https://www.fastcompany.com/3065420/at-sundar-pichais-google-ai-is-everything-and-everywhe',
		],
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'Vereidigung: Erste*r maschinelle*r Bundeskanzler*in',
		text: 'Das Bundeskanzler–Amt wird neu besetzt. Zum ersten Mal wählt die deutsche Bevölkerung AURORA, eine künstliche Intelligenz, die von nun an die Regierungsverantwortung trägt.',
		startDate: new Date('2111-10-31T23:00:00.000Z'),
		type: 'text',
		future: 'extreme',
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'In Luxemburg wird der letzte Mitarbeiter des öffentlichen Dienstes von Maschinen abgelöst',
		text: 'Laut dem Philosophen Richard David Precht wird sich beinahe jede Form konventioneller Arbeit in Zukunft durch Maschinen ersetzen lassen. Dies beinhaltet vor allem die Chance, Arbeiten zu tilgen, die sich rein durch ihre Vergütung erhalten müssen und nicht durch ein Interesse an der Arbeit selbst bestehen. ',
		startDate: new Date('2035-06-30T22:00:00.000Z'),
		type: 'text',
		future: 'extreme',
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: '„Intelligentes Maschinen- und Automatenschutzgesetz“ wird beschlossen',
		text: 'Oft unbeachtet bleibt neben der Frage, wie wir durch Gesetze die Menschen vor den Gefahren der künstlichen Intelligenz schützen können, auch die Frage, wie wir Maschinen selbst schützen wollen. Sollten Maschinen in Zukunft in der Lage sein, Bewusstsein und Emotionen zu entwickeln, ist eine ethische Diskussion nötig, welche die Frage klärt, wie wir die neu entstandenen Formen artifizieller Intelligenz unter der Wahrung von nötiger Würde behandeln.',
		startDate: new Date('2058-03-13T23:00:00.000Z'),
		type: 'text',
		future: 'extreme',
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'Siri verhindert Selbstmord',
		text: 'We are unbelievably proud to announce that today Siri has saved a life! #soproud #siri',
		startDate: new Date('2029-04-04T22:00:00.000Z'),
		type: 'social',
		future: 'extreme',
		tweet: true,
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'Adobe veröffentlicht AID – Gestalter*innen werden reihenweise entlassen',
		text: 'Nach mehreren Jahren von Misserfolgen schafft es Adobe ihren Service AID zu launchen. Der Dienst erlaubt es, ganze Designabteilungen auf nur wenige Gestalter herunterzubrechen. Diese können sich nun laut Adobe um "aufregendere" und "mehr relevante" Fragen des Designs und des Unternehmens kümmern. Auf die Frage, wie viele Kreative durch ein solches System arbeitslos werden, wollte Adobe nicht eingehen.',
		startDate: new Date('2042-03-31T22:00:00.000Z'),
		type: 'text',
		future: 'extreme',
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'Künstliche Intelligenz schreibt New York Times Bestseller',
		text: 'Justine, das nun weltweit bekannte KI–Autorensystem, erreichte heute mit ihrem Buch “Finding Dave“ den siebten Platz der New York Times Bestsellerliste. Das von Amazon & Google entwickelte System kombinierte den massiven Datensatz von 349 Millionen Büchern mit einem neuartigen Deep Learning Algorithmus, der die englische Sprache nicht nur versteht, sondern auch eine Wortgewandtheit und Eloquenz in den generierten Zeilen vorweist, die an einen jungen Kafka erinnern.',
		startDate: new Date('2035-12-31T23:00:00.000Z'),
		type: 'text',
		future: 'trend',
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'Künstliche Intelligenz unterstützt Lehrer*innen bei Klausur–Korrektur',
		text: 'Die weitreichend diskutierten Folgen des Lehrer*innenmangels lassen sich möglicherweise schon in näherer Zukunft mithilfe von KI abfangen. Denkbar wäre eine künstliche Intelligenz, welche Klausurkorrekturen entweder direkt selbst vornimmt, oder den Lehrer wesentlich dabei unterstützt. Das relevante Forschungsfeld der Schrifterkennung hat in den letzten Jahren bereits große Fortschritte gemacht, die sich beispielsweise mit einem Wissenssystem wie IBM Watson kombinieren lässt. So ließen sich auch geisteswissenschaftliche Fächer bis zu einem gewissen Grad automatisch korrigieren.',
		startDate: new Date('2021-08-31T22:00:00.000Z'),
		type: 'text',
		future: 'trend',
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'FH Potsdam führt neuen englischen Masterstudiengang “Designing AI“ ein',
		text: 'Nach zwei Jahren Entwicklungsphase im AI–Lab der FH Potsdam beginnen heute die ersten sechs Studierenden mit ihrem Studium im Master „Designing AI“.  Neben der Entwicklung von Nutzungskonzepten für künstliche Intelligenz und deren prototypische Entwicklung, beschäftigen sich die Studierenden hier vor allem auch mit dem Human Centered Design. Auch moralische und ethische Diskussionen sollen stattfinden.',
		startDate: new Date('2020-10-18T22:00:00.000Z'),
		type: 'text',
		future: 'trend',
	},
	{
		category: 'artificial-intelligence-deep-learning-machine-learning',
		title: 'Erstes autonomes Fahrzeug fährt von New York nach Los Angeles',
		text: '"I Want To Become An Actor" just arrived. First autonomous car driving across the country from NY to LA. Proud of the team.',
		startDate: new Date('2017-12-11T23:00:00.000Z'),
		type: 'social',
		future: 'trend',
		tweet: true,
	},
	{
		category: 'big-data',
		title: '"Ich habe nur gezeigt, dass es die Bombe gibt"',
		startDate: new Date('2016-12-02T23:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'https://www.dasmagazin.ch/2016/12/03/ich-habe-nur-gezeigt-dass-es-die-bombe-gibt/',
		],
	},
	{
		category: 'big-data',
		title: '"The end of privacy"',
		startDate: new Date('2017-03-24T23:00:00.000Z'),
		type: 'video',
		videourlFallsEinVideoHinzugefgtWerdenSoll: 'https://www.youtube.com/watch?v=DYhAM34Hhzc',
	},
	{
		category: 'big-data',
		title: '"Big Data allein entscheidet keine Wahl"',
		startDate: new Date('2016-12-05T23:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'http://www.zeit.de/digital/internet/2016-12/us-wahl-donald-trump-facebook-big-data-cambridge-analytica/komplettansicht',
		],
	},
	{
		category: 'big-data',
		title: 'Donald Trump wird US-Präsident',
		startDate: new Date('2016-11-08T23:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'http://www.zeit.de/politik/ausland/2016-11/donald-trump-wird-us-praesident',
		],
	},
	{
		category: 'big-data',
		title: ' The Power of Big Data and Psychographics',
		text: 'In einer Präsentation auf der Concordia Summit 2016 formuliert Alexander Nix, CEO der Firma Cambridge Analytica, die Nutzung von Big Data.',
		startDate: new Date('2016-09-18T22:00:00.000Z'),
		type: 'video',
		externalLinks: [
			'https://www.youtube.com/watch?v=n8Dd5aVXLCc&t=290s',
		],
	},
	{
		category: 'big-data',
		title: '"Diese Firma weiss, was sie denken"',
		text: 'Cambridge Analytica kann mit einer neuen Methode Menschen anhand ihrer Facebook-Profile minutiös analysieren. Und verhalf so Donald Trump mit zum Sieg.',
		startDate: new Date('2016-12-02T23:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'http://www.tagesanzeiger.ch/ausland/amerika/Diese-Firma-weiss-was-Sie-denken/story/25805157',
		],
	},
	{
		category: 'big-data',
		title: 'Die Luftpumpen von Cambridge Analytica',
		text: 'Nach der Wahl von Donald Trump gaben sich die Targeting-Experten von Cambridge Analytica alle Mühe, als wahlentscheidende Helfer dazustehen. Nun nehmen sie alles zurück.',
		startDate: new Date('2017-03-06T23:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'http://www.zeit.de/digital/internet/2017-03/us-wahl-cambridge-analytica-donald-trump-widerspruch',
		],
	},
	{
		category: 'big-data',
		title: 'Das OCEAN-Modell, die Big Five',
		text: 'Psychometrie, manchmal auch Psychografie genannt, ist der wissenschaftliche Versuch, die Persönlichkeit eines Menschen zu vermessen. In der modernen Psychologie ist dafür die sogenannte Ocean-Methode zum Standard geworden. Zwei Psychologen war in den 1980ern der Nachweis gelungen, dass jeder Charakterzug eines Menschen sich anhand von fünf Persönlichkeitsdimensionen messen lässt, den Big Five: Offenheit (Wie aufgeschlossen sind Sie gegenüber Neuem?), Gewissenhaftigkeit (Wie perfektionistisch sind Sie?), Extraversion (Wie gesellig sind Sie?), Verträglichkeit (Wie rücksichtsvoll und kooperativ sind Sie?) und Neurotizismus (Sind Sie leicht verletzlich?). Anhand dieser Dimensionen kann man relativ genau sagen, mit was für einem Menschen wir es zu tun haben, also welche Bedürfnisse und Ängste er hat, und aber auch, wie er sich tendenziell verhalten wird.\n\nFür den Warschauer Studenten Michal Kosinski begann ein neues Leben, als er 2008 an der ehrwürdigen Cambridge University in England aufgenommen wurde: am Zentrum für Psychometrie, im Cavendish Laboratory, dem ersten Psychometrie-Labor überhaupt. Mit einem Studienkollegen stellte Kosinski eine kleine App ins damals noch überschaubare Facebook: Auf MyPersonality, so hiess die Applikation, konnte man eine Handvoll psychologischer Fragen aus dem Ocean-Fragebogen ausfüllen und die Forscher bekamen die wertvollen persönlichen Daten.\n\n2012 erbringt Kosinski den Nachweis, dass man aus durchschnittlich 68 Facebook-Likes eines Users vorhersagen kann, welche Hautfarbe er hat (95-prozentige Treffsicherheit), ob er homosexuell ist (88-prozentige Wahrscheinlichkeit), ob Demokrat oder Republikaner (85 Prozent).',
		startDate: new Date('2016-12-02T23:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'https://www.dasmagazin.ch/2016/12/03/ich-habe-nur-gezeigt-dass-es-die-bombe-gibt/',
			'https://4f46691c-a-dbcb5f65-s-sites.googlegroups.com/a/michalkosinski.com/michalkosinski/Stillwell_and_Kosinski_2012.pdf?attachauth=ANoY7cqP9zIjyVccngnoDmS4HRY1HTiYIyda54F0W_8TGKsRHrBjI5ihZ8QfIpLx9n2Hw4vI9v7_M0CJjkVhcZKX12LHEHlGHDrM-x5RzpTnJgsknYcCJ7Kv4Hs4ckgrZsyyr1j0nWbPhhrdKHsJrruOLjw0M0RvZ2y3kC118E1EduZLcVvv--L_SNoC0-gDySNc_kj0XXPdbQn9ACIVGoqTdElw0HdlyzUhNQpkaUD88ruWhvtIcVQ6WCe1BIUFjfA9l5RVxEmx&attredirects=0',
		],
	},
	{
		category: 'portfolio-businessmodel-job-offers',
		title: 'Four Steps of Design Use – The Design Ladder',
		text: '»The Design Ladder« wurde vom Danish Design Center 2001 entwickelt. Sie veranschaulicht die unterschiedlichen Formen, die Design im Unternehmen einnehmen kann. Das Modell basiert auf der Hypothese, dass es einen positiven Zusammenhang zwischen höheren Erträgen und der Position von Design gibt. Besonders effizient erwies sich, von den frühen Entwicklungsstadien abzuweichen, Design mehr in den Vordergrund zu rücken und eine strategische Position in der Gesamtstrategie des Unternehmens einzuräumen.\n\n»The Design Ladder« besteht aus vier Schritten:\n1_Nicht-Design\n· Design ist unsichtbar im Unternehmen\n· ausgebildete Designer gibt es nicht\n· die Perspektive der Nutzer spielt eine geringe bis gar keine Rolle\n2_Design ist formgebend\n· Design findet in letzter Instanz statt, sei es in Bezug auf Produktentwicklung oder Grafikdesign\n· Designaufgaben werden in einigen Fällen von professionellen Designern durchgeführt, in der Regel aber von Personen mit anderem beruflichen Hintergrund behandelt\n3_Design als Prozess\n· Design ist nicht das Resultat, sondern ein Ansatz\n· Integriert wird Design in einem frühen Stadium des Entwicklungsprozesses \n· Die Lösung wird durch das Problem und die Benutzer angetrieben\n· eine Vielzahl von Fähigkeiten und Kapazitäten werden benötigt\n4_Design als Strategie\n· der Designer arbeitet mit den Eigentümern des Unternehmens, um das Geschäftskonzept ganz oder teilweise zu überdenken. \n· der Schwerpunkt liegt auf dem Designprozess in Bezug auf die Geschäftsvisionen des Unternehmens \n· Design ist ein Teil in der Wertschöpfungskette.',
		startDate: new Date('2000-12-31T23:00:00.000Z'),
		type: 'terminology',
		titleImage: 'http://danskdesigncenter.dk/sites/default/files/styles/full_width/public/section/images/design_ladder_2.png?itok=FoUkyw6f',
	},
	{
		category: 'portfolio-businessmodel-job-offers',
		title: 'How to get a Design Job at …',
		text: 'Der Designer Tobias van Schneider startet eine Serie an Interviews, in der Leuten aus anerkannten Firmen und Studios die Frage gestellt wird: »Wie bekomme ich einen Job in deinem Unternehmen?«',
		startDate: new Date('2017-03-02T23:00:00.000Z'),
		type: 'web',
		externalLinks: [
			'http://www.vanschneider.com/series/how-to-get-a-job-at/',
		],
	},
	{
		category: 'portfolio-businessmodel-job-offers',
		title: 'No Need for Designers',
		text: 'Der Designer von 2030 wird hauptsächlich Prozesse überwachen. Die gestalterische Arbeit wird durch Vorlagen und technische Neuerungen immer weniger. Die Informationsflut und rasante Entwicklung ermöglichen es, den Designer bald vollständig zu ersetzen.',
		startDate: new Date('2029-12-31T23:00:00.000Z'),
		type: 'text',
		future: 'extreme',
	},
	{
		category: 'portfolio-businessmodel-job-offers',
		title: 'Major Need for Designers',
		text: 'Der Designer ist 2030 zum unumgänglichen Mitarbeiter geworden. Durch sein Fachwissen macht er Produkte nutzbar. 90% der Neuerscheinungen auf dem Markt sind gestaltet. Neben dem Programmierer ist der Designer das wichtigste Glied im Unternehmen geworden, von dem maßgeblich der Erfolg abhängt.',
		startDate: new Date('2029-12-31T23:00:00.000Z'),
		type: 'text',
		future: 'trend',
	},
	{
		category: 'portfolio-businessmodel-job-offers',
		title: 'How to Get Hired: Understand If You’re an I, T, or X-Shaped Person',
		startDate: new Date('2016-10-04T22:00:00.000Z'),
		type: 'web',
		externalLinks: [
			'http://trydesignlab.com/blog/how-to-get-hired-understand-if-youre-an-i-t-or-x-s/',
		],
		titleImage: 'https://s3-us-west-2.amazonaws.com/storage.trydesignlab.com/blog/i-t-x-shaped-person-header-image-illustration.png',
	},
	{
		category: 'portfolio-businessmodel-job-offers',
		title: 'Photoshop S1.0 wird von Adobe exklusiv für den Apple Macintosh veröffentlicht',
		text: 'Adobe Photoshop war von Beginn an für die Bearbeitung von Bildern vorgesehen, die zuvor von einem Scanner digitalisiert wurden. Diese Geräte waren zur damaligen Zeit noch selten und teuer. \nIn der 1992 erschienenen Version waren bereits Pfadwerkzeuge enthalten. Mit Version 2.5 erschien im gleichen Jahr erstmals auch eine Version für Windows-Rechner.',
		startDate: new Date('1990-01-31T23:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'https://de.wikipedia.org/wiki/Adobe_Photoshop#Geschichte.2FEntwicklung',
		],
	},
	{
		category: 'portfolio-businessmodel-job-offers',
		title: 'It’s easier to teach design skills to the right people than to change the mindset of an accomplished craftsperson.',
		startDate: new Date('2016-12-17T23:00:00.000Z'),
		type: 'quote',
		externalLinks: [
			'https://blog.ajsmart.com/how-aj-smart-works-522e6be108e4',
		],
	},
	{
		category: 'portfolio-businessmodel-job-offers',
		title: 'Mehr Zeit dank Automatisierung',
		text: '»Wenn Systeme und Maschinen erledigen, wozu man bisher Menschen brauchte, dann bleibt denen mehr Zeit für Tätigkeiten, die nicht vorwiegend in eintöniger, stupider Wiederholung bestehen: für kreative Denkarbeit, Innovation, Tätigkeiten, die bisher nicht bezahlt wurden […] oder einfach für mehr Freizeit und Müßiggang.«',
		startDate: new Date('2017-02-28T23:00:00.000Z'),
		type: 'quote',
		externalLinks: [
			'https://www.brandeins.de/archiv/2017/neue-arbeit/wolf-lotter-neue-arbeit-einleitung-gute-arbeit/',
		],
	},
	{
		category: 'portfolio-businessmodel-job-offers',
		title: 'The Economic Effects of Design',
		text: 'Die Analyse »The Economic Effects of Design« ist einer der ersten gründlichen Ansätze, der das Verhältnis von Kosten und Nutzen bei der Verwendung von Design untersucht.',
		startDate: new Date('2003-08-31T22:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'https://erhvervsstyrelsen.dk/sites/default/files/the_economic_effects_of_designn.pdf',
		],
	},
	{
		category: 'portfolio-businessmodel-job-offers',
		title: 'Die unnötige Fragmentierung von Design Jobs',
		text: 'Was ist der Unterschied zwischen UX und UX/UI und UI? Ist Productdesign nicht UX/UI? Ist Front-End nicht UI? Was ist ein Grafik-Designer mit UX- & UI-Fokus? Und ist nicht all das visuelles, digitales Design?',
		startDate: new Date('2017-03-27T22:00:00.000Z'),
		type: 'web',
		externalLinks: [
			'https://m.signalvnoise.com/the-unnecessary-fragmentation-of-design-jobs-d5b9c8621082',
		],
		titleImage: 'https://cdn-images-1.medium.com/max/2000/1*1uq-iBxmUCe7e3EOrs7LGA.png',
	},
	{
		category: 'portfolio-businessmodel-job-offers',
		title: 'Hiring Trends in UX Design',
		text: '»UX designers are now as in demand as software engineers, and that demand is only going to increase.«',
		startDate: new Date('2017-02-02T23:00:00.000Z'),
		type: 'quote',
		externalLinks: [
			'https://blogs.adobe.com/creativecloud/hiring-trends-in-ux-design-the-6-things-you-need-to-know-about-techs-fastest-growing-field/',
		],
	},
	{
		category: 'design-thinking',
		title: 'Conference on Systematic and Intuitive Methods in Engineering, Industrial Design, Architecture and Communications',
		text: 'Die Konferenz hat zum einen die Entwicklung der Design Research Society inspiriert und bildet den Startpunkt für eine Bewegung, die sich damit beschäftigte Design eigenständig zu definieren und zu theoretisieren. Also inwiefern sich Design von Kunst und Handwerk unterscheidet.',
		startDate: new Date('1962-09-18T23:00:00.000Z'),
		type: 'event',
	},
	{
		category: 'design-thinking',
		title: 'Design Research Society',
		text: 'Im Jahre 1966 wurde die Design Research Society gegründet. Sie entstand aus dem Verlangen Design zu definieren und ihm eine eigene Stellung zu geben und beschreibt einen wissenschaftlichen Ansatz des Designs: Design Science.\nDer Sinn der Society, verkörperte sich in der Idee das studieren und untersuchen all der verschiedenen Design-Felder zu fördern. Und führte dadurch die Intention ein, eine interdisziplinäre, gelehrte Institution zu sein.',
		startDate: new Date('1966-06-30T23:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'http://www.designresearchsociety.org/cpages/home',
		],
	},
	{
		category: 'design-thinking',
		title: 'Buckminster Fuller',
		text: 'Einer der bekanntesten Vertreter der Design Science. Er beschrieb Design Science wie folgend:\n\n“Design Science is the effective application of the principles of science to the conscious design of our total environment in order to help make the Earth’s finite resources meet the needs of all humanity without disrupting the ecological processes of the planet”.\n\nSeine Teams waren elitär, exklusiv und prozessgetrieben. In Fullers Ansatz wurde Erfolg gemessen, so das jedes Projekt replizierbar ist.',
		startDate: new Date('1967-06-30T23:00:00.000Z'),
		type: 'quote',
		externalLinks: [
			'https://www.bfi.org',
		],
	},
	{
		category: 'design-thinking',
		title: 'Wicked Problems (Horst Rittel & Melvin Weber)',
		text: 'Rittel und Weber argumentierten eine strenge wissenschaftliche Sicht auf Gestaltungsprobleme. Sie führten den bekannten terminology „wicked problems“ ein.\nIn ihrem einflussreichen Paper „Dilemmas in a General Theory of Planning" beschreiben sie „wicked problems“ als einzigartige uneindeutige Probleme, die Designer nur klären, aber nicht lösen können. Diese Probleme haben offene und sich entwickelnde Variablen. Im Gegensatz dazu stehen herkömmliche wissenschaftliche Probleme, die eine definitive Antwort liefern können. Diese werden „tame problems“, zahme Probleme, genannt. Im Design gibt es demzufolge keine absolute Lösung und keine finalen wahren oder falschen Resultate.',
		startDate: new Date('1973-06-13T23:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'http://www.ask-force.org/web/Discourse/Rittel-Dilemmas-General-Theory-Planning-1973.pdf',
		],
	},
	{
		category: 'design-thinking',
		title: 'Viktor Papanek',
		text: 'Viktor Papanek führte Argumente für "socially conscious design" ein.\nEr vertrat die Notwendigkeit, mit innovativen nachhaltigen Lösungen, auf menschliche Bedürfnisse zu antworten. Mit der Errichtung einer Design Wissenschaft kamen prozessorientierte Methoden und standard Modelle einher. Papanek wollte die Aufmerksamkeit auf grundlegende gesellschaftliche Bedürfnisse zu lenken und damit auf die moralischen Verantwortungen von Designern.\n\n“Any attempt to separate design, to make it a thing by itself, works counter to the fact that design is the primary underlying matrix of life”.\n\nMit diesem Zitat richtet sich Papanek gegen Design als Wissenschaft.',
		startDate: new Date('1985-06-30T22:00:00.000Z'),
		type: 'quote',
	},
	{
		category: 'design-thinking',
		title: 'Cooperative Design',
		text: 'Das Co-Design entwickelte sich in den 1970er Jahren in Skandinavien. In den 80ern enstand es in ähnlicher Form unter dem Namen "participatory design" in den USA. Im Gegensatz zu den elitären Expertenteams in Amerika aber, die die Welt in Ordnung bringen wollen, laden die Skandinavier jeden ein, sich in die Diskussion einzubringen. Das geht in den Grundzügen bereits dorthin zurück, was wir heute Servicedesign nennen.\nDer sogenannte "collective resource" Ansatz entwickelte Strategien und Techniken für Arbeiter, um das Design und die Nutzung von Computern und deren Programmen am Arbeitsplatz zu beeinflussen.',
		startDate: new Date('1978-12-31T23:00:00.000Z'),
		type: 'event',
	},
	{
		category: 'design-thinking',
		title: 'Participatory Design',
		text: 'Was bereits in den 70ern in Skandinavien unter dem Namen "cooperative design" entstand, kam Mitte der 80er nach Amerika und wurde dort unter dem terminology partizipatives Design (participatory design) bekannt.\nGerüchte besagen, dass die Umbenennung stattgefunden hat, weil kooperativ, in seiner puren Form von inklusiver und demokratischer Gestaltung, in Amerika nicht funktionierte und die dortigen strikten Hierarchien unterlief.\nAnstelle von kooperativem gestalten / co-designen von Lösungen fanden weiterhin verschiedene Sessions für Arbeiter und Manager statt.',
		startDate: new Date('1985-06-14T22:00:00.000Z'),
		type: 'event',
	},
	{
		category: 'design-thinking',
		title: 'User Centered Design',
		text: 'Die nächste Episode in der Design-Entwicklung widmete sich unter dem terminology User-Centered Design endgültig der Rekontextualisierung von User Testings in eine Methode, die auch Bedürfnisse und Interessen der Nutzer erfassen wollte und stellte sie deswegen in den Mittelpunkt vom Designprozess.\nDer Fokus wurde also, statt ausschließlich auf Effizienz und Funktionalität des Artefakts auf die Nutzererfahrung gerichtet.\nInnovation wurde so nicht nur mit den Nutzern als Helfern gefunden, sondern mit ihnen als co-developer in größeren sozialen Kontexten.',
		startDate: new Date('1989-08-03T22:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'http://tubikstudio.com/faq-design-platform-human-centered-vs-user-centered-are-the-terms-different/',
		],
	},
	{
		category: 'design-thinking',
		title: 'Service Design',
		text: 'Die Aufmerksamkeit, die der Nutzererfahrung im User Centered Design geschenkt wurde half dabei eine nächste aufkommende Disziplin zu formen: Servicedesign.\nDie Definition von Servicedesign sieht alle Nutzer und Stakeholder\nals Designer von einem Service. Es befähigt sie, sich mit den Resultaten zu entwickeln und steht somit im Zeichen des cooperative design. Der Servicedesign Prozess entfernte sich von dem „Designer wissen alles“, hin zur Nutzung von ethnographischen Methoden für die Untersuchung von Menschen und deren Erfahrungen. So versucht die Methode alle Variablen und involvierten Personen zu verstehen.\n\nStatt Wert im Austausch steht der Wert im Nutzen.\nAnstelle von Produktion und Konsum stehen kontinuierliche Wertabfragen, anstelle von Wertschöpfungsketten stehen Wertschöpfungskonstellationen.\nStatt Autos zu gestalten wird der Dienst gestaltet, der Fahrten vermittelt.\nStatt das Begehren des Objekts herzustellen wird eine Beziehung zum Objekt hergestellt. Statt sich auf Nutzerfeundlichkeit und Zweckmäßigkeit auszuruhen, wird auch Haftung und Anpassung übernommen.',
		startDate: new Date('1989-12-31T23:00:00.000Z'),
		type: 'event',
	},
	{
		category: 'design-thinking',
		title: 'Human Centered Design',
		text: 'In den späten 90ern kam eine weitere Methodik hinzu. Human centered design.\nEs beschreibt den Prozess des Erstellens von Dingen, die sich auf die generellen natürlichen Eigenschaften des Menschen und dessen Psychologie und Wahrnehmung beziehen. Jedes Objekt kann so human-centered gestaltet sein und sich dabei begründen auf Psychologie, Physiologie, Soziologie und andere Wissenschaften, die das menschliche Leben und Interaktion mit der Umwelt beschreiben. \n\nSie baut auf emphatischer Designarbeit, die durch die frühen co-design Ansätze geformt sind. Die Empathie entsteht durch erhobene human-centered data und spielt eine entscheidende Rolle bei der Entscheidungs- und Innovationsfindung.',
		startDate: new Date('1995-05-04T22:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'http://tubikstudio.com/faq-design-platform-human-centered-vs-user-centered-are-the-terms-different/',
		],
	},
	{
		category: 'design-thinking',
		title: 'Design Thinking in 2017',
		text: 'Der terminology „Design Thinking“ im Gegensatz zu „Design“ erscheint neu und innovativ und hat Verwirrung darüber gestiftet ob Design Thinking nun eine neue Designdisziplin ist. Es ist die akkumulierte Geschichte der Designtheorie, der Methoden, Mindsets und Werkzeuge. Kontemporäres design thinking wird sowohl als Mindset aber auch als Methode beschrieben. Allerdings gilt es skeptisch zu bleiben, wer ein Design Thinker ist, ob die Methoden einzigartig sind und vor allem, ob wirklich Innovationen kreiert werden. Oberflächlich betrachtet unterscheidet eine mensch-zentrierte Philosophie Design Thinking von seinen methodischen Vorfahren. Dieser human-centered Ansatz wird als einer der wichtigsten Aspekte betrachtet.\n\n\nDie Methoden des Design Thinkings:\n\nHuman-centered:\nMenschen basiert, user- centered, einfühlsam, ethnographisch, Beobachtung.\n\nDenken durch machen:\nFrühes und schnelles prototypen, schnelles lernen, zügige iterative Entwicklungszyklen.\n\nVisualisieren:\nVisueller Ansatz, visuelles Denken.\n\nKollaborative Arbeitsweise:\nMultidisziplinäre Kollaborationen, viele Stakeholder involvierend.\n\n\nDie Denkweisen des Design Thinkings:\n\nAbduktives überlegen:\n„Was könnte sein“, neue Möglichkeiten finden, Verlangen etwas neues zu kreieren, Normen überdenken.\n\nGanzheitliche Sicht:\nIn Systemen denken, 360 Grad Blick auf das Thema.\n\nReflektierendes Reframing:\nProbleme umformulieren, hinter das Offensichtliche gehen: was liegt hinter dem Problem.\n\nIntegrative thinking:\nHarmonische Balance, kreative Lösung von Spannung, Gleichgewicht finden zwischen Validität und Verlässlichkeit.\n\n\nDie Mentalität des Design Thinkings:\n\nExperimentell und explorativ:\nMöglichkeiten erforschen, Scheitern riskieren, schnell scheitern.\n\nAmbiguität tolerierend:\nAmbiguität erlauben, fließender und offener Prozess.\n\nOptimistisch:\nBeschränkungen positiv bewerten, Gefallen am Problem lösen.\n\nPragmatisch:\nIntuitive und divergente Entscheidungen.\n\nZukunftsorientiert:\nVision vs. Status quo, Intuition als treibende Kraft.',
		startDate: new Date('2017-06-24T22:00:00.000Z'),
		type: 'terminology',
	},
	{
		category: 'design-thinking',
		title: 'Design Thinking löst Design auf',
		text: 'Designstudenten haben ihre speziellen Fähigkeiten aufgegeben, um in Unternehmensberatungen als Design-Thinker zu arbeiten. Andere Disziplinen haben aber auch die Methodiken des Design Thinkings erlernt und lösen, aufgrund ihrer ergänzenden Disziplin alle Designer in ihren Jobs ab und übernehmen die Gestaltung.',
		startDate: new Date('2050-12-30T23:00:00.000Z'),
		type: 'text',
		future: 'extreme',
	},
	{
		category: 'design-thinking',
		title: 'Design Thinking an Designschulen verboten',
		text: 'Designschulen entschließen sich einheitlich, Design Thinking in ihren Häusern nicht zu unterrichten. Die Methodik ist so allgemein, dass Lösungen allgemein und ungerechtfertigt werden und damit jeder Nachhaltigkeit entbehren.\n\nDie steigende Beliebtheit der Methode in der Finanzwelt trägt außerdem dazu bei, dass Studenten keine anderen gestalterischen Fähigkeiten mehr erlernen wollen.',
		startDate: new Date('2040-03-31T22:00:00.000Z'),
		type: 'text',
		future: 'extreme',
	},
	{
		category: 'design-thinking',
		title: 'Design Thinking als optionales Modul an Hochschulen',
		text: 'Obwohl Designstudenten das Design Thinking ohnehin indirekt im Studium erlernen entschließen sich einige Designschulen auf die Nachfrage im Markt zu reagieren und ihre Studenten entsprechend explizit im Design Thinking auszubilden und die konkreten Methoden in die Hand zu geben, mit denen sie die Nachfrage bedienen können. \n\nEs geht hierbei nicht um die tatsächlichen Denkweisen der Designer, sondern um die Formalisierung der Methode, um sie an andere Disziplinen verkaufen zu können.',
		startDate: new Date('2024-03-20T23:00:00.000Z'),
		type: 'text',
		future: 'trend',
	},
	{
		category: 'design-thinking',
		title: 'Hasso Plattner Institute (HPI) of Design at Stanford',
		text: 'In Palo Alto, an der Stanford University, gibt es seit dem 3. Oktober 2005 das Hasso Plattner Institute of Design. An der bislang „d.school“ genannten Einrichtung entwickeln Studenten einen Prozess für die Herstellung von kreativen Lösungen für die komplexesten Herausforderungen.',
		startDate: new Date('2005-11-02T23:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'https://dschool.stanford.edu/',
		],
	},
	{
		category: 'design-thinking',
		title: 'David M. Kelley',
		text: 'David M. Kelley ist Professor an der Stanford University sowie Gründer und Chairman von IDEO. Kelley gilt als Namensgeber und einer der Wegbereiter der Innovationsmethode Design Thinking',
		startDate: new Date('1951-02-09T23:00:00.000Z'),
		type: 'person',
		externalLinks: [
			'https://www.ideo.com/people/david-kelley',
		],
		titleImage: 'https://churchill.imgix.net/images/profiles/Kelley_David_Profile.jpg?auto=format&dpr=1&fit=max&w=700',
	},
	{
		category: 'design-thinking',
		title: ' HPI School of Design Thinking at Potsdam',
		text: 'Das Potsdamer Hasso-Plattner-Institut für Softwaresystemtechnik mit seiner HPI School of Design Thinking (tätig seit dem Wintersemester 2007/2008) pflegt mit seinem Schwesterinstitut in Stanford eine besonders enge Zusammenarbeit.\n\nNeben dem Austausch von Studenten und Wissenschaftlern gibt es einen jährlich stattfindenden Workshop zum Thema Design Thinking in Deutschland. Ebenso werden über die Achse zwischen Potsdam und Palo Alto deutsche Unternehmen in gemeinsame internationale Entwicklungsprojekte eingebunden. Mit Hilfe moderner Tele-Teaching-Technik wird die Durchführung solcher Projekte auf beiden Seiten des Atlantiks erleichtert. Außerdem gibt es einen Austausch von Lehrinhalten und anderen Materialien.',
		startDate: new Date('2007-09-30T22:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'https://hpi.de/das-hpi/uebersicht.html',
		],
		titleImage: 'https://hpi.de/fileadmin/user_upload/hpi/navigation/25_presse/25_bildmaterial/05_Fotos/10_campus/HPI_Hauptgebaeude_Tag_3054x2036.jpg',
	},
	{
		category: 'design-thinking',
		title: 'Interview mit der Design-Thinking-Ikone David Kelley',
		startDate: new Date('2010-10-26T22:00:00.000Z'),
		type: 'video',
		videourlFallsEinVideoHinzugefgtWerdenSoll: 'https://www.youtube.com/watch?v=cSMZ3ioQ7rc',
	},
	{
		category: 'design-thinking',
		title: '"Design & Thinking" the movie',
		text: 'In Bezug auf Design Thinking werden in diesem Dokumentarfilm Unternehmer, Designer, Sozialangagierte und unabhänige personen nach Ihrer Meinung befragt um ein gemeinsames Bild zu schaffen was sie von der mehrdeutigkeit des 21 Jahrhunders denken. Was ist Design Thinking? Wie wird es in Geschäftsmodelle angewendet? Wie werden die Menschen weltweit ihre eigene Kreativität ändern? Es ist ein Aufruf die übliche Meinung zu ändern und zusammenarbeiten.\n',
		startDate: new Date('2012-09-21T22:00:00.000Z'),
		type: 'video',
		externalLinks: [
			'http://www.designthinkingmovie.com/',
		],
		videourlFallsEinVideoHinzugefgtWerdenSoll: 'https://www.youtube.com/watch?v=uilcaXYnluU&feature=youtu.be',
	},
	{
		category: 'design-thinking',
		title: 'Case Studies: Using Design Thinking to Help Traditional German Butchers',
		text: 'Durch die Zunehmenden gezwungenen Schließung der Metzgereien zwischen 2004 und 2014 musste was Unternommen werden. Man brauchte neue Geschäftskonzepte für traditionelle Metzgereien in Deutschland. Die Ursachen des Problems und wie es durch Design Thinking gelöst wurde wird in diesem Artikel beschrieben ',
		startDate: new Date('2017-01-30T23:00:00.000Z'),
		type: 'web',
		externalLinks: [
			'http://thisisdesignthinking.net/2017/01/adalbertrapsstiftung_trueffeljagd/',
			'http://www.trueffeljagd.org/',
		],
		titleImage: 'http://innungen.mein-metzger-blog.de/wp-content/uploads/2016/10/dritte-trueffeljagd.jpg',
	},
	{
		category: 'design-thinking',
		title: 'Case Studies: Reinventing Solar Energy\u2028 Supply for Rural Africa',
		text: 'Eine junge Gründerszene bringt Afrika mit Ideen voran. Zugeschnitten auf lokale Probleme eröffnen sich auch Chancen für deutsche Start-ups wie Mobisol. Die Berliner Firma bietet Haushalten in Ostafrika kompakte Solarsysteme an, die ausreichend Strom für die Grundversorgung einer Familie liefern – also Licht, Radio und Handy. Größere Versionen können auch einen Kühlschrank oder Maschinen in Betrieben und Krankenhäusern betreiben. Der Artikel zeigt welche Auswirkungen Design Thinking auf eine Community haben kann.',
		startDate: new Date('2016-05-09T22:00:00.000Z'),
		type: 'web',
		externalLinks: [
			'http://thisisdesignthinking.net/2016/05/reinventing-solar-energy-supply-for-rural-africa/',
			'http://www.plugintheworld.com/mobisol/',
		],
		titleImage: 'http://eepafrica.org/wp-content/uploads/Mobisol-Replacing-kerosine.jpg',
	},
	{
		category: 'design-thinking',
		title: 'Case Studies: How ANA is Utilizing Design Thinking to Connect its Past with its Future',
		text: 'Eine Flugfirma verwendet Design Thinking um das Unternehmer zu überdenken',
		startDate: new Date('2016-12-11T23:00:00.000Z'),
		type: 'web',
		externalLinks: [
			'http://thisisdesignthinking.net/2016/12/ana-design-thinking-japan/',
		],
	},
	{
		category: 'design-thinking',
		title: 'Case Studies: Design Thinking at AirBnB',
		text: 'Wie eine Firma wie Airbnb Design Thinking benutzt. Nicht nur für den Enduser sonder auch für Ihre internen Methoden und Ihre Angestellten.',
		startDate: new Date('2015-05-11T22:00:00.000Z'),
		type: 'web',
		externalLinks: [
			'http://thisisdesignthinking.net/2015/05/airbnb-design-thinking-culture/',
		],
	},
	{
		category: 'design-thinking',
		title: 'Ted Talk: Design thinking for every endeavour by Robyn Richardson',
		text: 'Robyn behandelt den Unterricht wie ein musikalischer Auftritt.  Design Thinking unterrichten auf ihre eigene Weise durch die Wiederentdeckung der verlorenen Medien. Sie ermutigt Menschen sich in frage zu stellen was sie glaube zu wissen.',
		startDate: new Date('2014-06-10T22:00:00.000Z'),
		type: 'video',
		videourlFallsEinVideoHinzugefgtWerdenSoll: 'https://youtu.be/TPXrheqhTCs?list=PLdiAgEgVHpPdQbyT7-MYWpInInjoXsbmN',
	},
	{
		category: 'design-thinking',
		title: 'Ted Talk: Design Thinking: Solving Life’s Problems by Suresh Jayakar',
		text: 'Suresh Jayakar erzählt wie er als User Experience Designer ist es seine Aufgabe, mit Leuten zu sprechen, die Probleme zu hören, die sie haben, und die Technologie nutzen, um diese Probleme zu lösen mit der Verwendung von Design Thinking Methoden .',
		startDate: new Date('2017-01-16T23:00:00.000Z'),
		type: 'video',
		videourlFallsEinVideoHinzugefgtWerdenSoll: 'https://www.youtube.com/watch?v=UQYoWwHg3qA',
	},
	{
		category: 'design-thinking',
		title: 'Design Thinking in a NASA Study',
		text: 'Ende 2015 finanziert die NASA Luftfahrtforschung Mission Directorate (ARMD) ein Experiment in schnellem Design und schnellem Teaming. Das Ziel war es neue Ansätze zu erforschen, um anspruchsvolle Designprobleme in\nder Luftfahrt zu lösen. Dieser Bericht fasst mehrere Lektionen zusammen, welche sich auf die Studie beziehen.',
		startDate: new Date('2017-02-06T23:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20170001317.pdf',
		],
	},
	{
		category: 'design-thinking',
		title: 'Design Thinking in Mars',
		text: '\nWährend Trumps Präsidentschaft ist das erste Raumschiff auf dem Mars gelandet. Die Generation der Raumfahrer auf dem Mars haben sich in ihrem Jahre langen Training bereits mit Design Thinking Methoden auseinandergesetzt. Heutzutage sind diese Verfahren ein Schlüsselfaktor für den Erfolg der Zusammenarbeit des interdisziplinären wissenschaftlichen Teams.',
		startDate: new Date('2030-06-04T22:00:00.000Z'),
		type: 'text',
		future: 'extreme',
		externalLinks: [
			'https://jscfeatures.jsc.nasa.gov/jscfeatures/images/hires/jsc2004e45077-AsCanAnniv.jpg',
		],
	},
	{
		category: 'data-literacy',
		title: 'Wissensgesellschaft',
		text: 'Veränderung in der Gesellschaft, Übergang von der Industrie- zur "Wissensgesellschaft" (zeitlich in den 1950er bis 1060er-Jahren einzuordnen), Prägung des terminology in der Literatur erst später.',
		startDate: new Date('1964-12-31T23:00:00.000Z'),
		type: 'terminology',
	},
	{
		category: 'data-literacy',
		title: 'Fake News',
		text: '"Als Fake News […] werden lancierte bzw. veröffentlichte „vorgetäuschte Nachrichten“ bzw. Falschmeldungen bezeichnet, die sich überwiegend im Internet […] viral verbreiten und mitunter auch von Journalisten aufgegriffen werden. Zunehmend wurde Fake News auch zu einem politischen Schlagwort bzw. Kampfbegriff in der „Ära Trump“, ähnlich wie im deutschen „Lügenpresse“."',
		startDate: new Date('2016-10-31T23:00:00.000Z'),
		type: 'terminology',
		externalLinks: [
			'https://de.wikipedia.org/wiki/Fake_News',
		],
		mediaCredits: 'Wikipedia DE, CC-by-sa-3.0',
	},
	{
		category: 'data-literacy',
		title: 'Erste Website der Welt',
		text: 'Die erste Website der Welt, info.cern.ch, geht online. Sie erläutert das Konzept des "World Wide Web" und wurde vom britischen Wissenschaftler Tim Berners-Lee am CERN veröffentlicht.',
		startDate: new Date('1990-12-19T23:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'http://info.cern.ch/hypertext/WWW/TheProject.html',
			'http://home.cern/topics/birth-web',
		],
		titleImage: 'http://www.typolexikon.de/wp-content/uploads/2016/08/erste-website-im-world-wide-web-cern-1991-768x499.png',
	},
	{
		category: 'data-literacy',
		title: 'Wikipedia geht online',
		text: 'Die Website "www.wikipedia.com" geht online, als paralleles Projekt zur 1996 gegründeten "Nupedia". 2003 wurde die Wikimedia Foundation gegründet, die alle Rechte und die technische Infrastruktur von Wikipedia und Nupedia übernahm.',
		startDate: new Date('2001-01-14T23:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'https://de.wikipedia.org/wiki/Wikipedia:Enzyklopädie/Geschichte_der_Wikipedia',
		],
		mediaCredits: 'Wikipedia DE, CC-by-sa-3.0',
	},
	{
		category: 'data-literacy',
		title: 'Geburt des Internets',
		text: 'Tim Berners-Lee, der 1990 die erste Website der Welt veröffentlichte, reichte zuvor ein Proposal für ein "verteiltes Informationssystem" am CERN ein. Dies wird als die Geburt des Internets gesehen. ',
		startDate: new Date('1989-03-11T23:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'http://home.cern/topics/birth-web',
		],
	},
	{
		category: 'data-literacy',
		title: 'Erster Computer',
		text: 'Der von Konrad Zuse und Helmut Schreyer gebaute Computer "Zuse Z3" gilt als der erste funktionsfähige Digitalrechner der Welt.',
		startDate: new Date('1941-05-11T22:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'https://de.wikipedia.org/wiki/Zuse_Z3',
		],
		mediaCredits: 'Wikipedia DE, CC-by-sa-3.0',
	},
	{
		category: 'data-literacy',
		title: 'Erstes iPhone',
		text: 'Das erste iPhone der Firma Apple wurde 2007 von Steve Jobs auf der Macworld Conference in San Francisco vorgestellt.',
		startDate: new Date('2007-01-08T23:00:00.000Z'),
		type: 'event',
	},
	{
		category: 'data-literacy',
		title: 'Google geht online',
		text: 'Die Suchmaschine "Google" geht 1997 online.',
		startDate: new Date('1997-09-14T22:00:00.000Z'),
		type: 'event',
	},
	{
		category: 'data-literacy',
		title: 'YouTube geht online',
		text: 'Die Firma "YouTube" wurde 2005 gegründet, das erste Video wurde etwa zwei Monate später von einem der Gründer selbst hochgeladen.',
		startDate: new Date('2005-02-14T23:00:00.000Z'),
		type: 'event',
	},
	{
		category: 'data-literacy',
		title: 'Facebook geht online',
		text: 'Die Website "facebook.com" geht im Frühjar 2004 online, das Unternehmen wurde am 15. Februar gegründet.',
		startDate: new Date('2004-02-14T23:00:00.000Z'),
		type: 'event',
	},
	{
		category: 'data-literacy',
		title: 'Twitter geht online',
		text: 'Die Website "twitter.com" geht online, der erste Tweet wurde am 21. März von Mitgründer Dorsey gesendet und lautete "just setting up my twttr."',
		startDate: new Date('2006-03-20T23:00:00.000Z'),
		type: 'event',
	},
	{
		category: 'data-literacy',
		title: 'Gründung Fachhochschule Potsdam',
		text: 'Die Fachhochschule Potsdam wurde 1991 gegründet.',
		startDate: new Date('1990-12-31T23:00:00.000Z'),
		type: 'event',
	},
	{
		category: 'data-literacy',
		title: 'Gründung des Studienganges "Interfacedesign" an der FH Potsdam',
		text: 'Der Studiengang "Interfacedesign" an der Fachhochschule Potsdam wurde 2003 gegründet.',
		startDate: new Date('2002-12-31T23:00:00.000Z'),
		type: 'event',
	},
	{
		category: 'data-literacy',
		title: 'data-literacy',
		text: 'Der terminology wurde unter anderem durch Paul Gilster in seinem Buch "Digital Literacy" geprägt, das 1997 erschien.',
		startDate: new Date('1997-03-09T23:00:00.000Z'),
		type: 'text',
	},
	{
		category: 'data-literacy',
		title: 'Digital Natives',
		text: 'Menschen, die seit 1980 geboren wurden (und werden), sind "Digital Natives" – so schreiben zumindest John Palfrey und Urs Gasser in "Born Digital".',
		startDate: new Date('1979-12-31T23:00:00.000Z'),
		type: 'event',
	},
	{
		category: 'data-literacy',
		title: 'Millenials',
		text: 'Menschen, die etwa zwischen 1980 und 1995 geboren wurden, und die somit die Jahrtausendwende in jungem Erwachsenenalter bzw. als Kinder erlebten, werden als "Millenials" bezeichnet.',
		startDate: new Date('1979-12-31T23:00:00.000Z'),
		enddatumDesEintragsOptional: '1994-12-31T23:00:00.000Z',
		type: 'event',
	},
	{
		category: 'data-literacy',
		title: '"You are the product."',
		text: 'Erster Teil des Tweets von @chrisalbon vom 27.04.17:\n»2007: "You are the product."\n2017: "You are the training data."«\n\nEr beschreibt damit die Veränderung der Geschäftsmodelle im Web: Während mit dem Aufkommen sozialer Netzwerke wie Facebook oder Twitter die Nutzer*innen zum Produkt werden, weil sie im Tausch gegen die kostenlose Nutzung des Dienstes ihre Daten preisgeben, erfahren 2017 Machine Learning Algorithmen große Aufmerksamkeit, die mit großen Mengen von Nutzerdaten trainiert werden. Auf Basis dieser Daten können die Algorithmen unter anderem Verhaltensmuster erkennen und Ereignisse, wie beispielsweise Online-Käufe, mit hoher Genauigkeit voraussagen.',
		startDate: new Date('2006-12-31T23:00:00.000Z'),
		type: 'social',
		externalLinks: [
			'https://twitter.com/chrisalbon/status/857609299731791872',
		],
	},
	{
		category: 'data-literacy',
		title: '"You are the training data."',
		text: 'Zweiter Teil des Tweets von @chrisalbon vom 27.04.17:\n»2007: "You are the product."\n2017: "You are the training data."«\n\nEr beschreibt damit die Veränderung der Geschäftsmodelle im Web: Während mit dem Aufkommen sozialer Netzwerke wie Facebook oder Twitter die Nutzer*innen zum Produkt werden, weil sie im Tausch gegen die kostenlose Nutzung des Dienstes ihre Daten preisgeben, erfahren 2017 Machine Learning Algorithmen große Aufmerksamkeit, die mit großen Mengen von Nutzerdaten trainiert werden. Auf Basis dieser Daten können die Algorithmen unter anderem Verhaltensmuster erkennen und Ereignisse, wie beispielsweise Online-Käufe, mit hoher Genauigkeit voraussagen.',
		startDate: new Date('2016-12-31T23:00:00.000Z'),
		type: 'social',
		externalLinks: [
			'https://twitter.com/chrisalbon/status/857609299731791872',
		],
	},
	{
		category: 'data-literacy',
		title: 'Eshet-Alkalai. Digital Literacy: A Conceptual Framework for Survival Skills in the Digital era',
		text: 'Jl. of Educational Multimedia and Hypermedia (2004) 13(1),93-106.\n\nAbstract\nDigital literacy involves more than the mere ability to use software or operate a digital device; it includes a large variety of complex cognitive, motor, sociological, and emotional skills, which users need in order to function effectively in digital environments. The tasks required in this context include, for example, “reading” instructions from graphical displays in user interfaces; using digital reproduction to create new, meaningful materials from existing ones; constructing knowledge from a nonlinear, hypertextual navigation; evaluating the quality and validity of information; and have a mature and realistic understanding of the “rules” that prevail in the cyberspace. This newly emerging concept of digital literacy may be used as a measure of the quality of learners’ work in digital environments, and provide scholars and developers with a more effective means of communication in designing better user-oriented environments. This article proposes a holistic, refined conceptual framework for digital literacy, which includes photo-visual literacy; reproduction literacy; branching literacy; information literacy; and socio-emotional literacy.',
		startDate: new Date('2003-12-31T23:00:00.000Z'),
		type: 'text',
	},
	{
		category: 'data-literacy',
		title: 'Lankshear, Knobel. Digital Literacies: Concepts, policies and practices. Chapter 7: Martin. Digital Literacy and the “Digital Society"',
		startDate: new Date('2007-12-31T23:00:00.000Z'),
		type: 'text',
	},
	{
		category: 'data-literacy',
		title: 'Persike, Friedrich. Studie: Lernen mit digitalen Medien aus Studierendenperspektive',
		text: 'Studie aus dem Jahr 2016.\n\nZusammenfassung:\n"Die Studie zeigt, dass Studierende bei der Nutzung digitaler Medien zu einem Großteil eher konservativ agieren. Das Bild des vielseitig orientierten Studierenden, der sich aus dem umfangreichen Angebot verfügbarer Medien ein individuelles Lernportfolio zusammenstellt, entspricht unabhängig vom Alter der Studierenden nicht der breiten Realität. Die private Nutzung digitaler Medien übersetzt sich nicht zwangsläufig in den Hochschulalltag. Digitale Lehre funktioniert vor allem dann, wenn Dozierende sie proaktiv einführen. Diese Abhängigkeit des Digitalisierungsgrades vom Angebot wird in der vorliegenden Befragung am Beispiel der Informatikstudiengänge und der medizinischen Fächer gut sichtbar: Dort wo digitale Medien einen obligatorischen Bestandteil des Lernprozesses ausmachen, ist die Verbreitung bereits heute hoch."',
		startDate: new Date('2015-12-31T23:00:00.000Z'),
		type: 'text',
	},
	{
		category: 'data-literacy',
		title: 'Ng. Can we teach digital natives digital literacy?',
		text: 'Computers and Education (2012) 59(3),1065-1078\n\nAbstract\nIn recent years, there has been much debate about the concept of digital natives, in particular the differences between the digital natives\' knowledge and adoption of digital technologies in informal versus formal educational contexts. This paper investigates the knowledge about educational technologies of a group of undergraduate students studying the course Introduction to eLearning at a university in Australia and how they adopt unfamiliar technologies into their learning. The study explores the \'digital nativeness\' of these students by investigating their degree of digital literacy and the ease with which they learn to make use of unfamiliar technologies. The findings show that the undergraduates were generally able to use unfamiliar technologies easily in their learning to create useful artefacts. They need, however to be made aware of what constitutes educational technologies and be provided with the opportunity to use them for meaningful purposes. The self-perception measures of the study indicated that digital natives can be taught digital literacy.',
		startDate: new Date('2011-12-31T23:00:00.000Z'),
		type: 'text',
	},
	{
		category: 'data-literacy',
		title: 'Bildungspolitik Hochschulen & Universitäten',
		text: 'Die universitäre Bildung wird weitgehend digitalisiert, Lehrende nehmen vor allem die Rolle von Problemlösungs-Coaches ein. Die Wissensvermittlung findet über digitale Formate statt, die von aufgezeichneten Vorträgen an Spitzenuniversitäten bis zu interaktiven Lernplattformen reichen. Die Forschung ist Teil des "Digital First Mindset" und stellt ihre Daten und Forschungsaktivitäten als Open Access ins Web. Student*innen können daraus lernen und mit den Daten weiterarbeiten und erhalten virtuell Feedback zu eigenen Arbeiten und Forschungsfragen.',
		startDate: new Date('2029-12-31T23:00:00.000Z'),
		type: 'text',
		future: 'trend',
	},
	{
		category: 'data-literacy',
		title: 'Vernetzte Wirtschaft – oder auch nicht',
		text: 'Aufgrund von Sicherheitsbedenken schafft die vernetzte Produktion in Deutschland nicht den erwarteten Sprung und hängt innovationsfreudigen Ländern wie den USA oder China hinterher. In Deutschland werden vor allem Bauteile von Zulieferern produziert, mit hoher Präzision, jedoch mit geringer Flexibilität. In der deutschen Wirtschaft werden hochspezialisierte Ingenieur*innen gebraucht, die aufgrund der schlechten Bezahlung jedoch meist nach ihrer Ausbildung ins Ausland wechseln.',
		startDate: new Date('2026-12-31T23:00:00.000Z'),
		type: 'text',
		future: 'trend',
	},
	{
		category: 'data-literacy',
		title: 'Verfügbarkeit & Preis von mobilen Computern',
		text: 'Die Preise für mobile Computer fallen so stark, dass Schulen für jede*n Schüler*in Geräte bereitstellen können. Die Unterrichtsformate und auch der Einsatz von digitalen Medien im privaten Alltag verändern sich zugunsten interaktiver Einheiten. Virtuelle Lerncoaches können dank der hohen Rechenleistung individuell auf die Bedürfnisse der*des Schüler*in eingehen.',
		startDate: new Date('2023-12-31T23:00:00.000Z'),
		type: 'text',
		future: 'trend',
	},
	{
		category: 'data-literacy',
		title: 'Entwicklung von Webtechnologien',
		text: 'Echtzeit-VR-Anwendungen über das Web werden dank WebVR möglich, dadurch können Menschen weltweit miteinander arbeiten und lernen. Berufsfelder wie Architektur oder Design profitieren von kollaborativen VR-Anwendungen, wohingegen Geisteswissenschaften Probleme haben, Anwendungsfälle für diese Technologien zu finden. In diesem Bereich beschränken sich die Anwendungen meist auf generische Ansätze zur Wissensvermittlung.',
		startDate: new Date('2024-12-31T23:00:00.000Z'),
		type: 'text',
		future: 'trend',
	},
	{
		category: 'data-literacy',
		title: 'Angst statt Freiheit',
		text: 'Die Überwachung von Kommunikation im digitalen Raum nimmt zu und verschlüsselte Gespräche sind nicht mehr möglich. Sicherheitslücken in Software werden nicht mehr öffentlich bekanntgegeben und von Regierungen sowie Kriminellen ausgenutzt. Die mangelnde Sicherheit im Netz schränkt die Freiheit ein, kritische Konsumenten ziehen den offline-Einkauf vor, während unkritische Konsumenten bereitwillig ihre Daten preisgeben.',
		startDate: new Date('2022-12-31T23:00:00.000Z'),
		type: 'text',
		future: 'extreme',
	},
	{
		category: 'data-literacy',
		title: 'There is no Privacy',
		text: 'Alle Daten über jede Person sind öffentlich zugänglich, das Konzept der Privatsphäre ist vollständig von der Bildfläche verschwunden. Profitieren kann jede*r von diesen Daten, die*der es schafft, daraus Wert zu schöpfen, beispielsweise durch intelligente Verknüpfung von Datensätzen und gute User Experience.',
		startDate: new Date('2028-12-31T23:00:00.000Z'),
		type: 'text',
		future: 'extreme',
	},
	{
		category: 'data-literacy',
		title: 'Education Portfolios',
		text: 'Bildung ist hochgradig individualisiert, persönliche Education Portfolios zeigen den Werdegang einer*s jeden Einzelnen. Dies schafft Raum für hochspezialisierte Berufe, der Recruiting Prozess verändert sich dahingehend. Bildung ist aber auch eine Frage des Geldes: Anerkannte Zertifikate müssen teuer bezahlt werden.',
		startDate: new Date('2025-12-31T23:00:00.000Z'),
		type: 'text',
		future: 'trend',
	},
	{
		category: 'design-attitude',
		title: 'Ethik im Design',
		text: 'Diese Dokumentation ist das Ergebnis des Kurses Ethik im Studiengang Kommunikationsdesign an der HTW-Berlin. Im Wintersemester 2011/12 befragten die Studierenden dieses Kurses Designdienstleistende zu vorher erarbeiteten Fragen zur Ethik im Designberuf. Die einzelnen Interviews wurden in kleinen Teams durchgeführt.',
		startDate: new Date('2013-01-06T23:00:00.000Z'),
		type: 'video',
		videourlFallsEinVideoHinzugefgtWerdenSoll: 'https://vimeo.com/69492462',
	},
	{
		category: 'design-attitude',
		title: 'Gute Form, Böse Form',
		text: 'Ein spannender Artikel, erschienen im Süddeutsche Zeitung Magazin, zum Thema Design Ethik. Im Fokus des Artikels steht das Bauhaus, was sich in den 50er Jahren mit der Frage der Ethik im Design auseinandersetzten. Aber auch aktuelle Themen werden beleuchtet, z.B. die Gestaltung von modernen Autos.',
		startDate: new Date('2009-01-03T23:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'http://sz-magazin.sueddeutsche.de/texte/anzeigen/28958/Gute-Form-boese-Form',
		],
		titleImage: 'http://sz-magazin.sueddeutsche.de/upl/images/user/220586/thumbs_text/15525.jpg',
	},
	{
		category: 'design-attitude',
		title: 'Diskussionsrunde zum Thema Design Ethik',
		text: 'Eine Diskussionsrunde, ausgestrahlt im Radio München, zum Thema Ethik im Design. Zu Gast: die Designerin und Philosophin Manja Unger Büttner, Michael Lanz, Leiter des Instituts Industrial Design in Graz, Stephan Ott vom Designmagazin form und dessen Verleger Peter Wesner, Honorarprofessor für Wirtschaftsethik in Frankfurt.',
		startDate: new Date('2017-07-26T22:00:00.000Z'),
		type: 'audio',
		externalLinks: [
			'http://www.radiomuenchen.net/podcast-archiv/sendeformate/abends-unterwegs/654-design-und-ethik-im-ersten-sommersalon.html',
		],
	},
	{
		category: 'design-attitude',
		title: 'Design als Rhetorik: Grundlagen, Positionen, Fallstudien',
		text: 'Das Buch, "Design als Rhetorik" von Gesche Joost und Arne Scheuermann, stellt die klassische Kommunikationslehre der Rhetorik als eine neue und umfassende Metatheorie des Designs vor. Sie betrifft prinzipiell alle Bereiche heutigen Designs – vom Grafikdesign über die Architektur bis zur Interfacegestaltung. Sehr spannend und komplett zu lesen bei Google Books.',
		startDate: new Date('2008-07-02T22:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'https://books.google.de/books?id=HfbTAAAAQBAJ&pg=PA179&lpg=PA179&dq=design+ethik&source=bl&ots=bCwrLKjVcX&sig=XtxRrPPYuH2w2n84WbamgCQfWZ0&hl=en&sa=X&ved=0ahUKEwjIo6XVvtbUAhXNIVAKHRSADmY4FBDoAQgyMAU#v=onepage&q&f=false',
		],
	},
	{
		category: 'design-attitude',
		title: 'Interview mit Philippe Starck',
		text: 'In diesem Interview von Philippe Stark bestärkt er, dass der Designer eine wichtige ethische Aufgabe hat. Außerdem gibt er einen spannend Ausblick in die Zukunft: "Design wird verschwinden."',
		startDate: new Date('2009-03-31T22:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'http://sz-magazin.sueddeutsche.de/texte/anzeigen/28948/Philippe-Starck-Dem-Design-fehlt-Idealismus-und-Moral',
		],
	},
	{
		category: 'design-attitude',
		title: 'Jon Ivy wird "Chief Design Officer" von Apple',
		startDate: new Date('2015-05-25T22:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'https://techcrunch.com/2015/05/25/apple-names-jony-ive-chief-design-officer/',
		],
	},
	{
		category: 'design-attitude',
		title: 'Mike Monteiro über "Design Ethik"',
		text: 'Ein Artikel von Mike Monteiro, in dem er die ethischen Grundsätze vieler Designer angreift. Mike Monteiro ist Design Director von "Mule Design".',
		startDate: new Date('2017-03-18T23:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'https://deardesignstudent.com/ethics-cant-be-a-side-hustle-b9e78c090aee',
		],
	},
	{
		category: 'design-attitude',
		title: 'Michelle Stuhl über "Chief Design Officer"',
		text: 'In diesem Artikel von Michelle Stuhl, erschienen auf www.forbes.com erklärt die Autorin den Aufstieg des CDO in vielen großen Firmen. Darunter auch Namen wie Johnson & Johnson, Pepsi und Philips. Das ganze wird Forbes typisch aus einem ökonomischen Gesichtpunkt betrachtet.',
		startDate: new Date('2014-11-10T23:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'https://www.forbes.com/sites/groupthink/2014/11/11/what-is-behind-the-rise-of-the-chief-design-officer/#5e516b3733c2',
		],
	},
	{
		category: 'design-attitude',
		title: 'James Palister über "Chief Design Officer"',
		text: 'In diesem Artikel, von James Palister, geht es um die damals noch recht neue Position des "CDO". Er erklärt welche Firmen sich weshalb entschieden haben solch eine Position einzusetzen.',
		startDate: new Date('2015-04-26T22:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'http://www.designcouncil.org.uk/news-opinion/secrets-chief-design-officer-0',
		],
	},
	{
		category: 'design-attitude',
		title: 'No time at work? One meal will heal!',
		text: 'Kennen sie das? Zwischen den Meetings bleibt keine Zeit mehr zu essen? Sie fallen Abends hungrig ins Bett, weil sie wieder einmal den ganzen Tag nichts gegessen haben?\nDAMIT IST JETZT SCHLUSS!!!!\nHier kommt der all-in-one Protein Snack für zwischendurch, Maggi Powerfood, mit 2000 Kalorien, alles was sie für einen Tag brauchen.\nEntwickelt vom Marktführer im Bereich “ready-to-eat” Produkten, enthält ein Riegel alle Vitamine und Nährstoffe von zwei Mahlzeiten. In unser heutigen Zeit, in der 120 Stunden Wochen keine seltenheit mehr sind, ist das Essen nebenbei unersetzlich geworden. Das ganze kommt in sechs Geschmacksrichtungen, damit Sie an jedem Arbeitstag geschmackliche Abwechslung haben. Bestellen sie noch heute bei Amazon Prime Now direkt auf ihre Arbeitsstelle. Ab 7,99€ pro Maggi Powerfood Portion.',
		startDate: new Date('2024-02-15T23:00:00.000Z'),
		type: 'text',
		future: 'extreme',
		titleImage: 'https://lh3.googleusercontent.com/1O2rtMNJzVg5YsELgjxKiYJShfci4nIDmxXNttQ3E9hQLIfB_39_iTPq4iZgDn3jckDG4Wh30FrVCcokKFkHgD8blwO050fzqitQQsYYwdMNcrln-AkaIx1ygs2bWGsSK1I1IaWNtJl49AwzVPUgLFl1PNjv-MhzkGZsA6emNE4FdiHk7IeO_hkn3YsRC_5NmbcSC7np8wrKEmtTBRkmc2kw8qP3M9jFMDQYE_egyvumgP6CnxfIMng1NbKARqHQWdko4tWg7l5tl3w4JhRKPR5EY5Qu8XDEJLBAMLqpFBxselytQDb9dyD-0dvlSnMVW0HHoCgSIq-zsw8fvnsiEitjCgOBwrHCFD1okWvK00wIygGi4xiXGFH_ugBiAUaNo3i7HJo4aRHaYqhRqxloCHm7dQEv5CpGpCecswcMOms9F8_sMzT7jQfTUY0uZ0rQgTTl0bugAp2wO5vopoUJ-16veuL9aST_k9yoAW-zUfQ0-5kiKQ2owyqT6hoYyE355JYDJlH2wiiuXijtUS_k98xNIkVp4b9WUf3Wa9v7zis0Mw1EVCpcDAfGBJy5gd2I75k8AL8L=w2880-h1554 ',
	},
	{
		category: 'design-attitude',
		title: 'Wer versteht noch die Jugendlichen von heute?',
		text: 'Wer versteht noch die Jugendlichen von heute? Ich habe mich gerade wieder einmal mit meinem Sohn gestritten, ich möchte das ich ihn erreichen kann doch er verweigert sich da komplett. Ich habe ihm extra ein neues Handy gekauft, doch er sagt mir, dass in seiner Schule keiner mehr so etwas hat. Sie nennen mich wohl “Technologie Junkie” und verweigern sich dem digitalen komplett… \nDamals musste ich noch gegen meine Eltern kämpfen um ein Handy zu bekommen und jetzt lehnt er meine Großzügigkeit so ab?\nIch finde diesen neuen Trend der “Anti-Digitalen” Jugendlichen nicht gut, ich habe Angst um meine Kinder, ich weiß nicht immer wo sie sind. Was habt ihr für Ideen, wie ich meine kleinen wieder zum vernetzen überzeugen kann? Haben andere Eltern auch schon Erfahrungen damit gemacht?\nLiebe Grüße \nKevin B.\n \n15k likes',
		startDate: new Date('2030-10-17T22:00:00.000Z'),
		type: 'social',
		future: 'extreme',
		titleImage: ' http://www.gutefrage-gruppe.net/wp-content/uploads/jobs-gutefrage.png',
	},
	{
		category: 'design-attitude',
		title: 'Google schaut zu',
		text: 'Ein anonyme Nutzer-Leak hat Beweise veröffentlicht, welche zeigen, dass Google bereits seit März 2018 zugriff auf alle Überwachungskameras der Deutsche Regierung hat. Ob die Bundesregierung darüber in Kenntnis war ist noch unklar. Ein Statement von dieser Seite steht noch aus.\n \nGoogle hat in einer Stellungsnahme bekannt gegeben, die Daten ausschließlich für Werbezwecke einzusetzen, damit noch angepasstere Werbung für den einzelnen Benutzer, auf den Werbeplattformen dargestellt werden. Google sagt, dass sie natürlich Gesichtserkennung nutzen, diese aber anschließend anonimisieren, damit der einzelne geschützt ist. Ausschließlich der Google-Nutzername wird gespeichert und die Daten hiermit weiterverarbeitet.\n \nSeit dem 14.03.2019 ist das “Terror-Bekämpfungs-Gesetz”, unter der AFD Regierung, in Kraft getreten, welches Überwachungskameras in einer dichte von 5 Stück auf 100m² vorsieht. Dies geschah nach Londoner Vorbild und gilt auch für dünn besiedelte Gebiete, wie etwa Brandenburg. In Großstädten wie Berlin kommen sogar bis zu durchschnittlich 30 Kameras auf 100m².\n \nHeinz Buhrstett - Süddeutsche Zeitung',
		startDate: new Date('2027-09-13T22:00:00.000Z'),
		type: 'text',
		future: 'extreme',
		titleImage: 'https://cdn.pixabay.com/photo/2017/01/01/04/05/camera-1944039_1280.jpg ',
		mediaCredits: 'Pixabay - CC0 Public Domain',
	},
	{
		category: 'design-attitude',
		title: 'Stellenausschreibung: CDO Gesucht w/m',
		text: 'Since 2006 at neRosense, we have been developing innovative solutions inspired by all senses of the human body and soul. We mainly focus on understanding human sensibility and develop technologies and services that intensifies feelings, triggers deep excitements and immerses into powerful emotions. Using bioinformatics, sensory neuroscience, neuronal trained networks and teradata solutions, we aim to always be one step ahead of our competitors. As a fast-growing company with customers such as the NASA, NSA, Universal Studios Hollywood and the CERN, we are looking for strong personalities who wish to grow together with us in a dynamic work environment with short decision paths.\n \n**We are looking for a Sensorial Chief Design Officer (w/m)**\n \nAt neRosense you will become a member of a highly motivated Flexgile team located in our office at Port Moresby. We write well-tested, robust and code-generators and aim to find great solutions for challenging problems!\n \n**Your tasks**\n \n* You will lead, develop and design virtual odors and tastes experiences\n* You participate in all stages from design to release of a product.\n* You use modern technologies like doogal, tereminate, senslixir, …\n \n**You should have**\n \n* Basic skills in Sensory Neuroscience, Brain stimulation and Electroencephalography\n* At least a Master degree in Human centered experience design, very good design skills and at least two design specialities\n* Very good command of English, Chinese, Spanish and Hiri Motu\n* Very good skills in Rust, Elixir and Go\n* High level demands on the quality of your results\n* Excellent communication skills\n',
		startDate: new Date('2022-03-03T23:00:00.000Z'),
		type: 'text',
		future: 'extreme',
		titleImage: 'https://lh3.googleusercontent.com/i60KyGA3CVl944HBakA7WrIG4NjxahJhglw6C7MCIpzrP5f691d9HrRa-whKdbLYDrObFC8VUQONrr5Rb5ZPfg2B8QZ1GGy-JBy2ZdlZ5vgc5mQgl_0O3OH9ldultr-FZVYLPLQtxgzDIT0jZDzuOMWqKvoWu7Or9zj0dnvKGXqXPDASk85JD3f_nhR8duhjyop3fnRaCpfyv2liAqARwNSbI5emYzjuhcDqPWZK0GJIRg-TpPwF_29King8tF2sZKYISrXKqy32px5gTDfq64AavkIqVJqSZ75L8af79GUiQrbuK3Mxt8vz84tT7dK5BqYz8FoGuvd-rGgljR4aQXyRz2Ctp5Kh_CJjkfMtSre-PgQppFbviHTceorfbMhzecuAOf_8H4RUr7PSZkr8lW0OTONopzTfK6s_VrgGMVrk2a4K67ybSwxWKDKgvaAgwP4dFF9NVShUDCvdjJyh1-3sqvrIbHpbT_fYMJs0LuYe3lnahUBjYUF9uGeUusduRMbF8bOeAXP-K7ena3espkovn_rd4iou3-zj6l43uAkN0fPTw3pUtjTwfD5efZz7msK_EeNp=w2880-h1554 ',
	},
	{
		category: 'design-attitude',
		title: 'Mercedes selbstfahrende Autos',
		text: 'Seit mittlerweile einem Jahr sind die “Selbstfahrenden Taxis” vom Autobauer Mercedes Benz in Serie gegangen, in vielen Großstädten Deutschlands gehören sie zum Stadtbild dazu. Noch vor 10 Jahren klang das wie Zukunftsmusik, heute ist es Alltag. Wir nutzen die Fahrtzeit zum Beruf ganz anders, wir können bereits auf dem Weg zu unserer Arbeitsstelle mit der Arbeit beginnen und auf dem Weg nach Hause bereits unseren Feierabend genießen. Verkehrsnachrichten gehören, der Vergangenheit an, es gibt so selten Staus, dass diese Sektion komplett aus den Nachrichten verschwunden ist.\nUnsere Arbeitswege sind viel länger als früher, da wir die Fahrzeit zum Job sinnvoll nutzen können, sind 1-2 Fahrstunden keine große Hemmschwelle mehr. Auch wenn man manchmal noch kurz erschreckt, wenn sich die Person auf dem Fahrersitz noch einmal die Augen zu macht und sich zur Seite dreht, so ist das inzwischen zu einem normalen Bild geworden. ',
		startDate: new Date('2026-09-09T22:00:00.000Z'),
		type: 'text',
		future: 'trend',
		externalLinks: [
			'https://www.tagesschau.de/wirtschaft/daimler-bosch-autos-101.html',
		],
		titleImage: 'https://cdn.pixabay.com/photo/2016/11/21/16/30/automobile-1846301_1280.jpg',
		mediaCredits: 'Pixabay - CC0 Public Domain',
	},
	{
		category: 'design-attitude',
		title: 'The Invention of Leisure in Early Modern Europe',
		text: 'Im Februar 1995 wurde das Buch “The Invention of Leisure in Early Modern Europe” im Auftrag der “The Past and Present Society” von “Oxford University Press” veröffentlicht. Der Autor, Peter Burke, befasst sich darin mit den Anfängen der Verwendung des terminology “Leisure” (auf Deutsch: Freizeit oder Hobby) in Europa, welcher immer mehr im Kontrast zu der Arbeitszeit verwendet wird.',
		startDate: new Date('1995-01-31T23:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'http://www.jstor.org/stable/651154',
		],
		titleImage: 'https://lh3.googleusercontent.com/mMvajjS1wz4fBJr-dAVG8LA4Gav1Pj9n2FG2NG8ncFLcooWWQmP0RhoJxis_wvV14-gMjAScMbSP98Q1Ik174fD1pqZlUfY5TKrP0garN5dLD4ax0KpMxOvduQRYmpGS0aA1Mir8JQPlUWE0Ldf2iia7Rm4FOZDzq8EORyttUgp0i7poo1OVr70YYftxun1JnTqzTtcdhX2Rf03HcRjZwsC9h9LTh-lTPcKzQcQLSNjV4zuUTJ0HagdJDswYCGd1igwOlJk6951lvWLXiPCqZU3-NQ-UrMqR9llKA3p9i7ZUPv4TWyLxrjdxR5MGmJkFtA8e6ClP4EBwx8uK8fTaHoB3C46t9dK6DTWPPvmpNamkqz3xEjnkM5cfrCQrct7W_CTe7aV-vSVyHO84sfs0APGfrwwChqdKt95MoYIPQGoRzH7quw3b1komrh2VwQgwso2CR3Sxcd0ufAlGtUlHJCo-p6sW-GK49JAVDMAZaP0An1gVJhMCXlllcx5BJG09tUPQl-0ShjaAm9iZ03g8bYX7Jy-t9Lv9LZiSodsBld6ZjV3P_tsnPKHP51ooATesKGLRgumr=w1440-h1522',
		mediaCredits: '1995, Past & Present, The Past and Present Society',
	},
	{
		category: 'design-attitude',
		title: 'Work–Life Balance: Towards an Agenda for Policy Learning Between Britain and Germany',
		text: 'Die Deutsch-Britische Stiftung für das Studium der Industriegesellschaft hat in Oktober 2002 eine Studie veröffentlicht, welche die Work-Life Balance zwischen Großbritanien und Deutschland vergleicht. Der Autor, Lore Arthur, befasst sich in der Studie mit den politischen Kontexten, die Deutschland von Großbritanien unterscheidet und mit der theoretischen Konzepten von Zeit in Beziehung mit der Arbeits- und Familienwelt.',
		startDate: new Date('2002-09-30T22:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'http://oro.open.ac.uk/285/1/1381WorkLifeweb.pdf',
		],
		titleImage: 'https://lh3.googleusercontent.com/PjnQVePJOzPTh5xoVuryw-BcfNaCEudCXMbMPG7FgvYwQkHeLnG36kvFh2keqh5n4iXO_Q23f32OUJ_aSgcfYfL172PiRdknKVeJI11s027OlWmhmhgifXUTyrjxixmhPN6HVQDWLU-ZGx3Q1hdsFEn-9VGcOOQM3uwO3avFz97oQbDYAOz5AZrwsNVe6Xv5EJ5S_RsKQV-w_rmQVifEtJoJfc0H2qfyJBxPNI3Lg2EMSdzQ99hK9vNRSvihkN0ZRpW2Aj_f0bUOkeWzMbX5u_w5i3ICnFLUVlAE5mlzjagP93DBtbjQizgJDMOJSpJjX-D2ZxSzCjQVHWab123Mz2hTtpV7flXyV7X-B-Zrw9Vb-xQgnejVy-G1NgFxOgOO4qQj4QVM-29wk21EVAsP-u2Ct_Z6O-fYJxGjnkAyIqeMI641dI6OZtHuamTCm5Wi5Cj9_Ubao9NCZwGXFkxpY1sw-fbSHR9dFDpML_aecMELm-hGQlQGMUngpSClWLNkACccOy1uapj654mnczXOTbPJN8IivwwnNXkDxTcD8BjXVVteOo02EqYNvCvA22aSELr0W9ac=w1440-h1522',
		mediaCredits: '2002 Anglo-German Foundation',
	},
	{
		category: 'design-attitude',
		title: 'Designing the perfect Work-Life Balance',
		text: 'Im Blogartikel “Designing the perfect Work-Life Balance” von Cassius Kiani werden Tipps gegeben, wie Designer deren Work-Life Balance gestalten sollten.',
		startDate: new Date('2016-08-18T22:00:00.000Z'),
		type: 'web',
		externalLinks: [
			'https://www.invisionapp.com/blog/designing-work-life-balance/',
		],
		titleImage: 'http://s3.amazonaws.com/blog.invisionapp.com/uploads/2016/08/yourgoals.png?ver=1',
		mediaCredits: '2016, Cassius Kiani',
	},
	{
		category: 'design-attitude',
		title: 'Mein Leben gehört mir!',
		text: 'Die Grenze zwischen Arbeit und Privatem verschwimmt. Eine frühere Google-Mitarbeiterin, ein freier Designer und eine Schauspielerin erzählen, wie sie sich dagegen wehren.',
		startDate: new Date('2011-12-12T23:00:00.000Z'),
		type: 'web',
		externalLinks: [
			'http://millo.co/creating-a-healthy-work-life-balance-as-a-freelance-designer',
		],
		titleImage: 'https://lh3.googleusercontent.com/jnBLwVM8H99NYS0gQdUhAzbW5hjMiiHu9u0j6PEPmRSUnep9B9wOd3hcDtVhhqg_3bheLAXo-NM8UFXUftVK4PgOST-zQYlHDyWYO5FbbaXgNXiB9wJOJU90q72xzHjRXN7dAeNp3pH6jFdueoWDajnp7SlZMulMiL-xzDKctRgrT8F68FUz8rsd-FxsZN3FCR8hUoAXgMeedI2NtunZ7JcuFquMkyzTNZXJt8GH9KtVK3hF3MWrGDf6luJzxLQ2qKXm_0uN3_8rKniD2zths9X-En3FXoj6JaKJPjd2Zr10MD1mZLRyeQucNBwM4vdQ2fQez5H6cbzTfkQgZDvvjbJl9Ex99eFmWr1v6xpdwjH-c9P1ECE38S5GnKgwdIuYRMcKNyM1fKjZ8PLKnozkfXGnEgRut3k5Z2DNZb40Mw8okpqW3uyPYdb-sjf2OdXFahTnxBI-Is417eakNtWmIdBdIzTkJeBGzomfQ0HfitnhgqH9pib4COeFDC2m56HZFknfY8RlAQdqhMqHQS8QMzpC2H-sVLyyzpYSDX8qjFOawLakI4jvNkJ3926CG0VSHIuKb7Ba=w1440-h1522',
		mediaCredits: '2011, Brad Fitzgerald',
	},
	{
		category: 'design-attitude',
		title: 'Work in the 21st Century: The Role of I-O in Work–Life Programs',
		text: 'Karen May analysiert in ihrem Artikel die zunehmenden Formen von unterschiedlichen Work-Life Programmen und Firmen Angebote, wie flexible Arbeitszeiten, Arbeitsaufteilungen, Telekomunikation, Kinderbetreung, usw. und deren Auswirkungen auf das 21. Jahrhundert.',
		startDate: new Date('1998-10-01T22:00:00.000Z'),
		type: 'web',
		externalLinks: [
			'http://www.siop.org/tip/backissues/tipoct98/12may.aspx',
		],
		titleImage: 'https://lh3.googleusercontent.com/eBNMsEMV9mY91rw3d6MNEm_fzL7_fy8LoNc_ib7feiwDu6Z4beWWfAtcqbaS38eqc7jhK8UH61xDm-2C3vvQC4QUc2F6tlvOzdPgaXSuCJFnrmc93NjX9NhGm1Ko5IqYf5UvoKgfpfwnvqi3HuU5QRg_A5y6X6KijKJjCvaNgQEb-9BMAvCTguoc223IkeWssM9BZCQpuY7ZMUkz23Z1-99gs0T4aVeCl1CkIqCJ_S4-LvaQFQnG89Q8DyiBoFJgD8shFJOrkw-_-XMzav6mIHb91tjFD6afCfA7RGn3tRnQmDKrLPeUPpoN2zokg8VvBg5Ma_i1QMQZQhBaKXtONsWf07ZKMKFw4PaHwpGAus18-bUMinACU479wbkTU5whATSHQrwZJeB4CrVMaoAJxgodC_QwE0YYAsj7afx8PDPKbBbfYQ2w1_5Ehs9J_xwIWgFAF7Fap_fKVxgjVeO8SnlL6ALGzc9aZTaTIPURxC_3TXow5lXA1HZsF6zJl18amayqh0AP_lzyexJ-6JE-tnKNEl37WHCHnAeKwA2GqG9YvrrBK2RoMU2LjQawEzLMNl-rYbkF=w1440-h1522',
		mediaCredits: '1998, Karen May',
	},
	{
		category: 'design-attitude',
		title: 'Open Letter Urges Facebook to Strenghen Privacy',
		text: 'Eine Gruppe von Konsumentenbefürwortungsgruppen denkt, dass Facebook in Bezug auf ihre Datenschutzerklärung weiter gehen könnte, und schickte Facebook CEO Mark Zuckerberg einen offenen Brief, in dem sie ihre spezifischen Anliegen aufzeigen. Und überraschend hat Facebook Punkt für Punkt geantwortet.',
		startDate: new Date('2017-06-16T22:00:00.000Z'),
		type: 'web',
		externalLinks: [
			'https://www.digitaltrends.com/computing/open-letter-urges-facebook-to-strengthen-privacy/',
		],
		titleImage: 'https://lh3.googleusercontent.com/SAPEbiCDlgm9muTCtT2fmswvcWcfC1nhZVrI_CetqvAsM83PV_b0wv5ddzrTBx2g0kaiPQBvsHY8BlCUjp0adtr166R0H6WYmBt-KS-CRqF0Y4R-Gzz3lX7gsSUgRVLAGr6fHUaDhLgiaRR3d6ClSaBVuCU2Kxne3koa4u8XVjrNMLbxexuNw0yM5FxZB4qnQgsmflZBvOEE4Ik9HflMjMQxDgatiRQAXAcNp4E1MdPy1qmw_SEsU_BUjrAAgCyYNZ01rO4h3t0qdUjgCSfvEpQyM4LeYQHtNopjpqylXAq-J1kbMoouHhJiLdIc8sVcqKnypczmAghVFI3D6GnNDmcLWjyN2PxREbe27N8zFl8QrNUxPomRoP6FiJHuS2Bia5cpvnmFOefF2XterlPhxK4h_vdvwOR6aKBxDlzp4ZDSCtNg9zVn7BLXjQM14_Op-90bA4qz-KqD8zX_DV7zL1lXGiwM2CF9IOQtOEmGY7jo2CmqnhGabKv-t9bmrpqQxNOtqLEbg28i18GeTO-AraJK8ux3q7o3pnO33K2qE4xb6nVI4z4bBHgMGpuGP9AQhmoSVq3b=w1440-h1522',
	},
	{
		category: 'design-attitude',
		title: 'Erward Snowden über Privatshäre',
		text: 'Speak not because it is safe, but because it is right.',
		startDate: new Date('2017-02-10T23:00:00.000Z'),
		type: 'social',
		titleImage: 'https://pbs.twimg.com/profile_images/648888480974508032/66_cUYfj.jpg',
		mediaCredits: '2017, Twitter',
	},
	{
		category: 'design-attitude',
		title: ' Ratifizierung der Bill of Rights',
		text: 'Die “Bill of Rights” werden ratifiziert. Während des zwanzigsten Jahrhunderts halten Gerichte fest, dass mehrere Schutzmaßnahmen für bestimmte Aspekte der Privatsphäre sowie das Recht auf Privatsphäre laut des  “First Amendment” und ein Recht auf Privatsphäre in US-amerikanischen Haushalten laut des “Third Amendment” unter den gesetzlichen Garantien vorliegen.\nDas “Fourth Amendment” garantiert Personen und deren Eigentum das Recht auf Sicherung vor unangemessenen Recherchen und Beschlagnahmungen und wird vom Obersten Gerichtshof im Jahre 1967 interpretiert, um ein Recht auf Privatsphäre zu schützen.',
		startDate: new Date('1971-12-14T23:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'http://www.shmoop.com/right-to-privacy/timeline.html',
		],
		titleImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Bill_of_Rights_Pg1of1_AC.jpg/1920px-Bill_of_Rights_Pg1of1_AC.jpg',
		mediaCredits: '1789, National Archives and Records Administration',
	},
	{
		category: 'design-attitude',
		title: 'The Evolution of Privacy, Identity, and Forgiveness',
		text: 'Vorhersage: Transparenz erhöht individuelle Integrität und Vergebung. Im Jahr 2020 sind die Menschen noch offener und gewillt persönliche Informationen, Meinungen und Emotionen zu teilen, als sie jetzt sind. Die Privatsphäre der Öffentlichkeit hat sich geändert. Die Menschen sind in der Regel bereit, die Vorteile der Anonymität gegen die Vorteile, die sie in den geteilten Daten von anderen Menschen und Organisationen wahrnehmen auszutauschen. Da das Leben der Menschen transparenter geworden ist, sind sie für ihre eigenen Handlungen verantwortlich geworden und vergeben mehr der teilweise unethischen Vergangenheit von Anderen. "Geoutet" für eine alte “Sünde” in einem YouTube-Video oder andere durchdringende Medienform zu sein schadet nicht so sehr wie es im ersten Jahrzehnt des 21. Jahrhunderts der Fall war. Sorgfältige Untersuchungen, Reputationskorrekturen und Klarstellungen zu formulieren, sind tägliche Aufgaben der wichtigsten Medien Webseiten geworden.',
		startDate: new Date('2019-12-31T23:00:00.000Z'),
		type: 'text',
		future: 'trend',
		externalLinks: [
			'http://www.pewinternet.org/2008/12/14/scenario-4-the-evolution-of-privacy-identity-and-forgiveness/',
		],
		titleImage: 'https://lh3.googleusercontent.com/rimnmJnK9M0JluZzCqLR-_sWgjd5YsRrxzss13pANdGx7pfgIYGIsvcxmE_Ou9TO-i63ma6y8S5AUob0vWnfdr718vq--l8Ola301jgc4JaMD9qADuRRg7bKG7LqtEhLx0NdP8P_4QO9DRhYsPe-KYZ4J_jnLGJLqT1vrpEF4H8luEHLX65-dRzPEj6lheeFRSyKyFnq5VIj2fXGft8t3pZdKtLMnd81DK4kSs6aEL6QTTdi53qlKDjRxHqc9zkr0ArQ-u7GUDJA2m_heFTE-h83XPitZd4bJZEU3fmQw28dXPZd58qsZuctxdxFXrUc5vwC3DP4WtznKi-ivsS3yJUEYmW9ICXdpRBCiB6tFU4al0UjF8ifbnBC3-lTUnLHPQR1eAkiNeI5_aicn_mnWuNoJrl8ytowwifeaXM1rVXRrp7ka_mQwP_rnOpzTM3f1cOe1UKp2lidjXHe4ZiFbvqfLpPHyTqKToluXjYObN4p_PMusR8yRmq0JL-U-efVXABNdXsy96ewmyrn5SNl8OJZ_zJuvXJFZQ-hT47sAB9vwMDRGxSBKa4j7zCc778_5QXqonhC=w2880-h1554',
		mediaCredits: '2008, Lee Rainie & Janna Anderson',
	},
	{
		category: 'design-attitude',
		title: 'Google chief: Only miscreants worry about net privacy',
		text: 'Im Dezember 2009, nachdem Privatsphäre-Anliegen erhoben wurden, erklärte der Chef von Google, Eric Schmidt,: "Wenn Sie etwas tun und nicht wollen, dass es jemand erfährt, sollten Sie es vielleicht an erster Stelle nicht tun. Wenn Sie wirklich solcher Art von Privatsphäre brauchen, müssten Sie die Realität bewusst sein, nämlich dass Suchmaschinen, einschließlich Google, Informationen für einige Zeit behalten. Es ist wichtig zu verstehen, zum Beispiel, dass wir alle in den Vereinigten Staaten in die “Patriot Act” unterziehen und dass es möglich sei, dass alle diese Informationen den Behörden zur Verfügung gestellt werden."',
		startDate: new Date('2009-12-06T23:00:00.000Z'),
		type: 'text',
		titleImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Eric_Schmidt_at_the_37th_G8_Summit_in_Deauville_037.jpg/896px-Eric_Schmidt_at_the_37th_G8_Summit_in_Deauville_037.jpg ',
		mediaCredits: 'Wikipedia - CC BY 3.0',
	},
	{
		category: 'design-attitude',
		title: 'Sagmeister & Walsh protestieren gegen Trump',
		text: 'New work! We created over 40 limited edition pins that protest Trump, promote love, tolerance & kindness. Check out http://Pinswontsavetheworld.com .',
		startDate: new Date('2017-02-10T23:00:00.000Z'),
		type: 'social',
		externalLinks: [
			'https://twitter.com/sagmeisterwalsh/status/780857580201635840 ',
		],
		titleImage: 'https://pbs.twimg.com/ext_tw_video_thumb/780857540619997184/pu/img/YJqyGn9mv9kdkaLY.jpg ',
	},
	{
		category: 'new-work',
		title: 'Gründung des ersten Zentrums für Neue Arbeit',
		text: 'Frithjof Bergmann gründet das erste Zentrum für Neue Arbeit in Michigan, USA',
		startDate: new Date('1983-12-31T23:00:00.000Z'),
		enddatumDesEintragsOptional: '1984-12-30T23:00:00.000Z',
		type: 'event',
	},
	{
		category: 'design-niche',
		title: 'T-Shape Model – David Guest',
		text: 'The hunt for a new breed of computer manager is on. The British Computer Society, in a controversial report published last year, described the quarry as a “hybrid” manager who would combine business expertise with IT skills. The hybrid manager, it said, would be distinguished by his or her ability to relate to “the broad picture” and to people, understanding their motivation and aspirations; he or she would also be energetic, intuitive, a good listener, and (cryptically) would have “an unusual set of interests”. \n\nThis type of rounded personality is also sought in other branches of the same theory, which prizes individuals known as T-shaped People. These are a variation on Renaissance Man, equally comfortable with information systems, modern management techniques and the 12-tone scale.\n\nDavid Guest, “The hunt is on for the Renaissance Man of computing,” The Independent (London), September 17, 1991',
		startDate: new Date('1991-09-16T22:00:00.000Z'),
		type: 'event',
	},
	{
		category: 'design-niche',
		title: 'T-shape Model – Tom Brown',
		text: 'Tim Brown is the CEO and president of IDEO.\nHis book "Change By Design" introduces design thinking, the collaborative process,  viable business strategies and how the techniques and strategies of design belong at every level of business. ',
		startDate: new Date('2010-01-20T23:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'http://chiefexecutive.net/ideo-ceo-tim-brown-t-shaped-stars-the-backbone-of-ideoaes-collaborative-culture__trashed/',
		],
	},
	{
		category: 'design-niche',
		title: 'T-/I-/X-shape Modul - Definition',
		text: 'T-Shape: \n“The T-shaped person has broader skills and knowledge and learns by linking up different perspectives from different specialties.”\n\nI-Shape:\n“If your skills are I-shaped, you have deep knowledge and experience in one area, but haven’t applied those skills to other areas.”\n“The traditional educational system is built to produce I-shaped people.”\n\nX-Shape:\n“Great leaders are rooted in the depth of both their subject knowledge and their professional esteem and credibility.”\n“They are focused on strategy and team management, rather than the coalface design work.”',
		startDate: new Date('2016-01-08T23:00:00.000Z'),
		type: 'terminology',
		externalLinks: [
			'http://trydesignlab.com/blog/how-to-get-hired-understand-if-youre-an-i-t-or-x-s/',
			'https://medium.com/@trydesignlab/how-to-get-hired-understand-if-you-re-an-i-t-or-x-shaped-person-58f440f9a29',
		],
	},
	{
		category: 'design-niche',
		title: 'Are You an "I" or a „T“?',
		startDate: new Date('2010-10-17T22:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'https://www.forbes.com/sites/andyboynton/2011/10/18/are-you-an-i-or-a-t/#21ec37ed6e88',
		],
	},
	{
		category: 'design-niche',
		title: 'T-Academy ',
		text: 'T-Summit History\n\nIn March 2014, leaders from higher education, industry, government, foundations, and professional associations met in San Jose, California to discuss how to design innovative educational models that foster and develop T-shaped characteristics that are in high demand today and in the future workforce. The summit generated dynamic discussions regarding how higher education and industry can collaborate to cultivate the talent development required for the 21st century workforce. T-shaped professionals need educational and work experiences that help them to learn on how to handle information from multiple sources; advance professional relationships across organizations; contribute innovatively to organizational practices; and communicate with understanding across social, cultural, economic and scientific boundaries.\n\nT-Summit 2015, held on the campus of Michigan State University in March 2015, pushed the conversation further to determine how these groups can best work together to prepare students to be professionals who use new technologies, business models, and societal innovation to make a positive impact on the world.\n\nParticipants at this event discussed: higher education and employer partnerships that develop T-shaped competencies; employer practices that advance T-shaped competencies; higher education partnerships that promote T-shaped education; metrics and competencies that define the "T"; and cultivating entrepreneurs and innovators. Participants in the second annual T-Summit shared experiences and best practices to create a common language for both higher education and the corporate sector to use synonymously surrounding T-shaped development. ',
		startDate: new Date('2014-02-28T23:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'http://tsummit.org/t',
			'http://tsummit.org/about',
		],
		titleImage: 'http://tsummit.org',
	},
	{
		category: 'design-niche',
		title: 'T-Shaped Innovators: Identifying the Right Talent to Support Service Innovation',
		startDate: new Date('2015-08-31T22:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'https://www.questia.com/library/journal/1G1-428875322/t-shaped-innovators-identifying-the-right-talent',
		],
	},
	{
		category: 'design-niche',
		title: 'Freiberufler – Statistik',
		text: 'Teilzeitbeschäftigung: Jede siebte Teilzeitkraft hat den Wunsch nach Mehrarbeit',
		startDate: new Date('2017-01-09T23:00:00.000Z'),
		type: 'web',
		externalLinks: [
			'https://www.destatis.de/DE/ZahlenFakten/GesamtwirtschaftUmwelt/Arbeitsmarkt/Erwerbstaetigkeit/Erwerbstaetigkeit.html',
		],
	},
	{
		category: 'design-niche',
		title: 'Bundesverband der Freien Berufe e.V.',
		text: 'Die BFB-Mitgliederversammlung hat 1995 folgende Definition des „Freien Berufs“ verabschiedet, die die in ihren wesentlichen Punkten Eingang in die Legaldefinition des § 1 Abs. 2 S. 1 Partnerschaftsgesellschaftsgesetz sowie in die Rechtsprechung des Europäischen Gerichtshofs (EuGH) gefunden hat.: "Die Freien Berufe haben im Allgemeinen auf der Grundlage besonderer beruflicher Qualifikation oder schöpferischer Begabung die persönliche, eigenverantwortliche und fachlich unabhängige Erbringung von Dienstleistungen höherer Art im Interesse der Auftraggeber und der Allgemeinheit zum Inhalt."',
		startDate: new Date('1994-12-31T23:00:00.000Z'),
		type: 'web',
		externalLinks: [
			'https://www.freie-berufe.de/ueber-die-freien-berufe/daten-und-fakten.html',
			'https://www.freie-berufe.de/ueber-die-freien-berufe/definition-und-profil.html',
		],
		titleImage: 'https://www.freie-berufe.de/ueber-die-freien-berufe/daten-und-fakten.html',
	},
	{
		category: 'design-niche',
		title: 'Selbstständigkeit – Einkommensteuergesetz (EStG) § 18 ',
		startDate: new Date('2011-12-06T23:00:00.000Z'),
		type: 'text',
		externalLinks: [
			'https://www.gesetze-im-internet.de/estg/__18.html',
		],
	},
	{
		category: 'design-niche',
		title: 'Fachhochschule Potsdam: Akkreditiert! „Analog Living – B.A.“ ab WS 2030',
		text: 'Fachhochschule Potsdam: Akkreditiert! „Analog Living – B.A.“ ab WS 2030\n#bringinganalogeback #fhpotsdamrules #future',
		startDate: new Date('2030-04-14T22:00:00.000Z'),
		type: 'social',
		future: 'extreme',
		tweet: true,
	},
	{
		category: 'design-niche',
		title: 'Ab 2030 - FH Bibliothekstandort schließt für immer',
		text: 'Fachhochschule Potsdam | 15. April 2030\nAb 2030 - FH Bibliothekstandort schließt für immer\n... erfahren Sie mehr',
		startDate: new Date('2029-12-31T23:00:00.000Z'),
		type: 'text',
		future: 'trend',
	},
	{
		category: 'design-niche',
		title: 'NA2030',
		text: 'NA2030: We are proud to announce the winners of this years „Niche Award 2030“ soon! \n#NA2030 #nicheistheshit #nichewinners',
		startDate: new Date('2030-08-19T22:00:00.000Z'),
		type: 'social',
		future: 'trend',
		tweet: true,
	},
	{
		category: 'design-niche',
		title: 'Gründung der ecosign Design Akademie',
		text: '1994 wird die Ecosign Akademie in Köln gegründet. Mit ihrem Fokus auf nachhaltiges Design positioniert sie sich in einem wachsenden Konkurrenzmarkt privater Designhochschulen, und bediente dadurch ein Nischenthema, das bis heute immer mehr an Bedeutung gewonnen hat.',
		startDate: new Date('1994-09-30T23:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'https://www.ecosign.de/',
		],
		titleImage: 'https://www.ecosign.de/de-wAssets/img/content/die-ecosign/ueber-die-akademie/galerie/weblication/wThumbnails/02-ecosign-fassade-f2ad49d69147d46g1b37ac76b1f0cbf3.jpg',
		mediaCredits: 'ecosign.de',
	},
	{
		category: 'design-niche',
		title: 'CODE Hochschule Berlin',
		text: 'Zum Wintersemester 2017 soll die CODE Hochschule Berlin ihre Pforten öffnen. Das Lehrkonzept richtet sich vor allem an zukünftige Internet-Unternehmer, und bildet in den Bereichen Software Engineering, Interaction Design und Product Management aus. Diese sehr spezifische, wirtschaftsorientierte Ausrichtung steht deshalb auch in der Kritik.',
		startDate: new Date('2016-09-13T22:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'https://code.berlin/',
		],
		titleImage: 'https://code.berlin/content/uploads/9bf31c7f-1000x667.jpg',
		mediaCredits: 'www.code.berlin',
	},
	{
		category: 'design-niche',
		title: 'Gründung der Agentur Darkhorse',
		text: 'Dark Horse ist eine Agentur aus Berlin. Mit 30 Gründern aus 25 Disziplinen berät sie Unternehmen im Bereich Design Thinking und Service Design. Außerdem bieten sie sogenanntes „Culture Hacking“ an, indem sie Unternehmen von innen heraus beobachten und daraus Veränderungen schaffen. Dark Horse war eine der ersten Agenturen in Berlin, die Design Thinking als spezifisches Angebot an Unternehmen verkauft hat.',
		startDate: new Date('2008-12-31T23:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'http://www.thedarkhorse.de/',
		],
	},
	{
		category: 'design-niche',
		title: 'Gründung von Dunne & Raby',
		text: 'Dunne & Raby ist ein Londoner Design-Studio, gegründet von Anthony Dunne und Fiona Raby. Anders als herkömmliche Designstudios zielen ihre Arbeiten darauf ab, durch Design Debatten über soziale, kulturelle und ethische Fragen anzustoßen. Dunne & Raby etablierten Methoden wie Design Fiction, Speculative Design, Design for Debate und Critical Design.',
		startDate: new Date('1993-12-31T23:00:00.000Z'),
		type: 'event',
		externalLinks: [
			'http://www.dunneandraby.co.uk/',
		],
		titleImage: 'http://www.dunneandraby.co.uk/img/projects/large/cover.jpg',
		mediaCredits: 'www.dunneandraby.co.uk',
	},
	{
		category: 'design-niche',
		title: 'Erneuerung des Grundschulsystems',
		text: 'Europaweit tritt zum neuen Schuljahr eine grundlegende Änderung in Kraft: Ab der zweiten Klasse werden nun sogenannte Spezialisierungsfächer eingeführt, die die Schüler – basierend auf der Vorschule und ihrem ersten Schuljahr – selbstständig wählen. Anstatt einer umfassenden Gesamtausbildung erhalten die Schüler nun schon früher die Möglichkeit, sich in einem speziellen Themengebiet zu vertiefen. Durch das frühe Einschlagen einer gezielten Richtung verspricht sich die Bildungsministerin zukünftig mehr Experten in Nischen-Fachrichtungen. (dpa)',
		startDate: new Date('2023-07-31T22:00:00.000Z'),
		type: 'text',
		future: 'trend',
	},
	{
		category: 'design-niche',
		title: 'FH Potsdam stellt Designstudiengang ein',
		text: 'Die Fachhochschule Potsdam stellt als erste Hochschule Deutschlands ihr breites Studienangebot im Fach Design ein. „Wir haben beobachtet, dass Design sich immer mehr als Management-Beruf entwickelt hat“, so die Dekanin des Fachbereichs, der sich mit neuen Studiengangskonzepten von der bisherigen Designpraxis trennen wird, und einen größeren Fokus auf Wirtschaft, Management und Beratung legen wird. Es ist zu erwarten, dass auch weitere Hochschulen diesem Beispiel folgen werden, und Nischen-Praktiken der Gestaltung nicht mehr Hochschulthema sein werden.',
		startDate: new Date('2028-09-30T22:00:00.000Z'),
		type: 'text',
		future: 'extreme',
	},
	{
		category: 'design-niche',
		title: 'Designstudiengänge an der FH Potsdam werden zusammengelegt',
		text: 'Ab dem kommenden WS22/23 bieten wir nur noch *einen* DESIGN-Studiengang – anstatt vieler unterteilter Fachbereiche – an. @FHPotsdam',
		startDate: new Date('2022-03-31T22:00:00.000Z'),
		type: 'social',
		future: 'trend',
		tweet: true,
	},
	{
		category: 'design-niche',
		title: 'Neuer Studiengang NAILDESIGN',
		text: 'Call for Entries! Bewerben Sie sich für ein Stipendium im neuen Studiengang NAILDESIGN (unser 20. Fachbereich!). #findyourniche @dsgnAKDmy',
		startDate: new Date('2019-05-24T22:00:00.000Z'),
		type: 'social',
		future: 'extreme',
		tweet: true,
	},
];

export default rawEvents.map((data) => ({
	data: Object.assign({}, {
		title: '',
		text: '',
		category: 'big-data',
		type: 'text',
		startDate: new Date(),
		titleImage: undefined,
		video: undefined,
		mediaCredits: undefined,
		future: undefined,
		externalLinks: [],
	}, data),
	id: uuid(),
	state: {
		selected: false,
		hovered: false,
	},
}));
